const hanziData = {
    1: [
    { word: "一", zhuyin: "ㄧ" },
    { word: "二", zhuyin: "ㄦˋ" },
    { word: "四", zhuyin: "ㄙˋ" },
    { word: "五", zhuyin: "ㄨˇ" },
    { word: "六", zhuyin: "ㄌㄧㄡˋ" },
    { word: "七", zhuyin: "ㄑㄧ" },
    { word: "八", zhuyin: "ㄅㄚ" },
    { word: "九", zhuyin: "ㄐㄧㄡˇ" },
    { word: "十", zhuyin: "ㄕˊ" },
    { word: "日", zhuyin: "ㄖˋ" },
    { word: "月", zhuyin: "ㄩㄝˋ" },
    { word: "山", zhuyin: "ㄕㄢ" },
    { word: "木", zhuyin: "ㄇㄨˋ" },
    { word: "水", zhuyin: "ㄕㄨㄟˇ" },
    { word: "人", zhuyin: "ㄖㄣˊ" },
    { word: "手", zhuyin: "ㄕㄡˇ" },
    { word: "門", zhuyin: "ㄇㄣˊ" },
    { word: "小", zhuyin: "ㄒㄧㄠˇ" },
    { word: "上", zhuyin: "ㄕㄤˋ" },
    { word: "走", zhuyin: "ㄗㄡˇ" },
    { word: "左", zhuyin: "ㄗㄨㄛˇ" },
    { word: "右", zhuyin: "ㄧㄡˋ" },
    { word: "向", zhuyin: "ㄒㄧㄤˋ" },
    { word: "魚", zhuyin: "ㄩˊ" },
    { word: "也", zhuyin: "ㄧㄝˇ" },
    { word: "來", zhuyin: "ㄌㄞˊ" },
    { word: "加", zhuyin: "ㄐㄧㄚ" },
    { word: "船", zhuyin: "ㄔㄨㄢˊ" },
    { word: "前", zhuyin: "ㄑㄧㄢˊ" },
    { word: "油", zhuyin: "ㄧㄡˊ" },
    { word: "開", zhuyin: "ㄎㄞ" },
    { word: "出", zhuyin: "ㄔㄨ" },
    { word: "招", zhuyin: "ㄓㄠ" },
    { word: "車", zhuyin: "ㄔㄜ" },
    { word: "子", zhuyin: "ㄗˇ" },
    { word: "花", zhuyin: "ㄏㄨㄚ" },
    { word: "地", zhuyin: "ㄉㄧˋ" },
    { word: "在", zhuyin: "ㄗㄞˋ" },
    { word: "笑", zhuyin: "ㄒㄧㄠˋ" },
    { word: "印", zhuyin: "ㄧㄣˋ" },
    { word: "張", zhuyin: "ㄓㄤ" },
    { word: "臉", zhuyin: "ㄌㄧㄢˇ" },
    { word: "泡", zhuyin: "ㄆㄠˋ" },
    { word: "玩", zhuyin: "ㄨㄢˊ" },
    { word: "大", zhuyin: "ㄉㄚˋ" },
    { word: "起", zhuyin: "ㄑㄧˇ" },
    { word: "好", zhuyin: "ㄏㄠˇ" },
    { word: "多", zhuyin: "ㄉㄨㄛ" },
    { word: "我", zhuyin: "ㄨㄛˇ" },
    { word: "的", zhuyin: "ㄉㄜ˙" },
    { word: "朵", zhuyin: "ㄉㄨㄛˇ" },
    { word: "你", zhuyin: "ㄋㄧˇ" },
    { word: "抱", zhuyin: "ㄅㄠˋ" },
    { word: "吹", zhuyin: "ㄔㄨㄟ" },
    { word: "像", zhuyin: "ㄒㄧㄤˋ" },
    { word: "爸", zhuyin: "ㄅㄚˋ" },
    { word: "到", zhuyin: "ㄉㄠˋ" },
    { word: "青", zhuyin: "ㄑㄧㄥ" },
    { word: "叫", zhuyin: "ㄐㄧㄠˋ" },
    { word: "下", zhuyin: "ㄒㄧㄚˋ" },
    { word: "那", zhuyin: "ㄋㄚˋ" },
    { word: "和", zhuyin: "ㄏㄜˊ" },
    { word: "要", zhuyin: "ㄧㄠˋ" },
    { word: "他", zhuyin: "ㄊㄚ" },
    { word: "朋", zhuyin: "ㄆㄥˊ" },
    { word: "友", zhuyin: "ㄧㄡˇ" },
    { word: "跟", zhuyin: "ㄍㄣ" },
    { word: "頭", zhuyin: "ㄊㄡˊ" },
    { word: "想", zhuyin: "ㄒㄧㄤˇ" },
    { word: "做", zhuyin: "ㄗㄨㄛˋ" },
    { word: "外", zhuyin: "ㄨㄞˋ" },
    { word: "住", zhuyin: "ㄓㄨˋ" },
    { word: "個", zhuyin: "ㄍㄜˋ" },
    { word: "們", zhuyin: "ㄇㄣ˙" },
    { word: "這", zhuyin: "ㄓㄜˋ" },
    { word: "裡", zhuyin: "ㄌㄧˇ" },
    { word: "有", zhuyin: "ㄧㄡˇ" },
    { word: "沒", zhuyin: "ㄇㄟˊ" },
    { word: "是", zhuyin: "ㄕˋ" },
    { word: "什", zhuyin: "ㄕㄣˊ" },
    { word: "麼", zhuyin: "˙ㄇㄜ" },
    { word: "星", zhuyin: "ㄒㄧㄥ" },
    { word: "哪", zhuyin: "ㄋㄚˇ" },
    { word: "球", zhuyin: "ㄑㄧㄡˊ" },
    { word: "家", zhuyin: "ㄐㄧㄚ" },
    { word: "河", zhuyin: "ㄏㄜˊ" },
    { word: "金", zhuyin: "ㄐㄧㄣ" },
    { word: "說", zhuyin: "ㄕㄨㄛ" },
    { word: "句", zhuyin: "ㄐㄩˋ" },
    { word: "話", zhuyin: "ㄏㄨㄚˋ" },
    { word: "兩", zhuyin: "ㄌㄧㄤˇ" },
    { word: "都", zhuyin: "ㄉㄡ" },
    { word: "悄", zhuyin: "ㄑㄧㄠˇ" },
    { word: "尾", zhuyin: "ㄨㄟˇ" },
    { word: "巴", zhuyin: "ㄅㄚ" },
    { word: "滿", zhuyin: "ㄇㄢˇ" },
    { word: "紅", zhuyin: "ㄏㄨㄥˊ" },
    { word: "吐", zhuyin: "ㄊㄨˇ" },
    { word: "缸", zhuyin: "ㄍㄤ" },
    { word: "搖", zhuyin: "ㄧㄠˊ" },
    { word: "春", zhuyin: "ㄔㄨㄣ" },
    { word: "貼", zhuyin: "ㄊㄧㄝ" },
    { word: "呢", zhuyin: "˙ㄋㄜ" },
    { word: "了", zhuyin: "˙ㄌㄜ" },
    { word: "請", zhuyin: "ㄑㄧㄥˇ" },
    { word: "天", zhuyin: "ㄊㄧㄢ" },
    { word: "家", zhuyin: "ㄐㄧㄚ" },
    { word: "把", zhuyin: "ㄅㄚˇ" },
    { word: "不", zhuyin: "ㄅㄨˋ" },
    { word: "房", zhuyin: "ㄈㄤˊ" },
    { word: "福", zhuyin: "ㄈㄨˊ" },
    { word: "流", zhuyin: "ㄌㄧㄡˊ" },
    { word: "三", zhuyin: "ㄙㄢ" },
    { word: "幸", zhuyin: "ㄒㄧㄥˋ" }
  
    ],

    2: [
    { word: "充", zhuyin: "ㄔㄨㄥ" },
    { word: "太", zhuyin: "ㄊㄞˋ" },
    { word: "電", zhuyin: "ㄉㄧㄢˋ" },
    { word: "雨", zhuyin: "ㄩˇ" },
    { word: "過", zhuyin: "ㄍㄨㄛˋ" },
    { word: "後", zhuyin: "ㄏㄡˋ" },
    { word: "為", zhuyin: "ㄨㄟˋ" },
    { word: "冬", zhuyin: "ㄉㄨㄥ" },
    { word: "土", zhuyin: "ㄊㄨˇ" },
    { word: "草", zhuyin: "ㄘㄠˇ" },
    { word: "冒", zhuyin: "ㄇㄠˋ" },
    { word: "哭", zhuyin: "ㄎㄨ" },
    { word: "心", zhuyin: "ㄒㄧㄣ" },
    { word: "陽", zhuyin: "ㄧㄤˊ" },
    { word: "機", zhuyin: "ㄐㄧ" },
    { word: "顏", zhuyin: "ㄧㄢˊ" },
    { word: "色", zhuyin: "ㄙㄜˋ" },
    { word: "細", zhuyin: "ㄒㄧˋ" },
    { word: "著", zhuyin: "ㄓㄨㄛˊ" },
    { word: "問", zhuyin: "ㄨㄣˋ" },
    { word: "鳥", zhuyin: "ㄋㄧㄠˇ" },
    { word: "綠", zhuyin: "ㄌㄩˋ" },
    { word: "看", zhuyin: "ㄎㄢˋ" },
    { word: "藍", zhuyin: "ㄌㄢˊ" },
    { word: "空", zhuyin: "ㄎㄨㄥ" },
    { word: "媽", zhuyin: "ㄇㄚ" },
    { word: "彩", zhuyin: "ㄘㄞˇ" },
    { word: "中", zhuyin: "ㄓㄨㄥ" },
    { word: "虹", zhuyin: "ㄏㄨㄥˊ" },
    { word: "蜻", zhuyin: "ㄑㄧㄥ" },
    { word: "蜓", zhuyin: "ㄊㄧㄥˊ" },
    { word: "音", zhuyin: "ㄧㄣ" },
    { word: "樂", zhuyin: "ㄩㄝˋ" },
    { word: "會", zhuyin: "ㄏㄨㄟˋ" },
    { word: "坡", zhuyin: "ㄆㄛ" },
    { word: "忙", zhuyin: "ㄇㄤˊ" },
    { word: "布", zhuyin: "ㄅㄨˋ" },
    { word: "場", zhuyin: "ㄔㄤˇ" },
    { word: "入", zhuyin: "ㄖㄨˋ" },
    { word: "口", zhuyin: "ㄎㄡˇ" },
    { word: "河", zhuyin: "ㄏㄜˊ" },
    { word: "林", zhuyin: "ㄌㄧㄣˊ" },
    { word: "間", zhuyin: "ㄐㄧㄢ" },
    { word: "風", zhuyin: "ㄈㄥ" },
    { word: "跑", zhuyin: "ㄆㄠˇ" },
    { word: "置", zhuyin: "ㄓˋ" },
    { word: "書", zhuyin: "ㄕㄨ" },
    { word: "打", zhuyin: "ㄉㄚˇ" },
    { word: "跳", zhuyin: "ㄊㄧㄠˋ" },
    { word: "陪", zhuyin: "ㄆㄟˊ" },
    { word: "去", zhuyin: "ㄑㄩˋ" },
    { word: "險", zhuyin: "ㄒㄧㄢˇ" },
    { word: "海", zhuyin: "ㄏㄞˇ" },
    { word: "找", zhuyin: "ㄓㄠˇ" },
    { word: "歡", zhuyin: "ㄏㄨㄢ" },
    { word: "神", zhuyin: "ㄕㄣˊ" },
    { word: "奇", zhuyin: "ㄑㄧˊ" },
    { word: "猜", zhuyin: "ㄘㄞ" },
    { word: "次", zhuyin: "ㄘˋ" },
    { word: "誰", zhuyin: "ㄕㄨㄟˊ" },
    { word: "跟", zhuyin: "ㄍㄣ" },
    { word: "恐", zhuyin: "ㄎㄨㄥˇ" },
    { word: "龍", zhuyin: "ㄌㄨㄥˊ" },
    { word: "豚", zhuyin: "ㄊㄨㄣˊ" },
    { word: "喜", zhuyin: "ㄒㄧˇ" },
    { word: "帶", zhuyin: "ㄉㄞˋ" },
    { word: "氣", zhuyin: "ㄑㄧˋ" },
    { word: "球", zhuyin: "ㄑㄧㄡˊ" },
    { word: "始", zhuyin: "ㄕˇ" },
    { word: "吹", zhuyin: "ㄔㄨㄟ" },
    { word: "突", zhuyin: "ㄊㄨ" },
    { word: "然", zhuyin: "ㄖㄢˊ" },
    { word: "得", zhuyin: "ㄉㄜ˙" },
    { word: "高", zhuyin: "ㄍㄠ" },
    { word: "樹", zhuyin: "ㄕㄨˋ" },
    { word: "給", zhuyin: "ㄍㄟˇ" },
    { word: "可", zhuyin: "ㄎㄜˇ" },
    { word: "理", zhuyin: "ㄌㄧˇ" },
    { word: "只", zhuyin: "ㄓˇ" },
    { word: "輕", zhuyin: "ㄑㄧㄥ" },
    { word: "飛", zhuyin: "ㄈㄟ" },
    { word: "還", zhuyin: "ㄏㄞˊ" },
    { word: "居", zhuyin: "ㄐㄩ" },
    { word: "孩", zhuyin: "ㄏㄞˊ" },
    { word: "常", zhuyin: "ㄔㄤˊ" },
    { word: "躲", zhuyin: "ㄉㄨㄛˇ" },
    { word: "發", zhuyin: "ㄈㄚ" },
    { word: "現", zhuyin: "ㄒㄧㄢˋ" },
    { word: "就", zhuyin: "ㄐㄧㄡˋ" },
    { word: "頭", zhuyin: "ㄊㄡˊ" },
    { word: "回", zhuyin: "ㄏㄨㄟˊ" },
    { word: "想", zhuyin: "ㄒㄧㄤˇ" },
    { word: "但", zhuyin: "ㄉㄢˋ" },
    { word: "怎", zhuyin: "ㄗㄣˇ" },
    { word: "知", zhuyin: "ㄓˋ" },
    { word: "道", zhuyin: "ㄉㄠˋ" },
    { word: "先", zhuyin: "ㄒㄧㄢ" },
    { word: "鄰", zhuyin: "ㄌㄧㄣˊ" },
    { word: "縮", zhuyin: "ㄙㄨㄛ" },
    { word: "讓", zhuyin: "ㄖㄤˋ" },
    { word: "畫", zhuyin: "ㄏㄨㄚˋ" },
    { word: "愛", zhuyin: "ㄞˋ" },
    { word: "送", zhuyin: "ㄙㄨㄥˋ" },
    { word: "寫", zhuyin: "ㄒㄧㄝˇ" },
    { word: "祝", zhuyin: "ㄓㄨˋ" },
    { word: "張", zhuyin: "ㄓㄤ" },
    { word: "臉", zhuyin: "ㄌㄧㄢˇ" },
    { word: "感", zhuyin: "ㄍㄢˇ" },
    { word: "謝", zhuyin: "ㄒㄧㄝˋ" },
    { word: "老", zhuyin: "ㄌㄠˇ" },
    { word: "啊", zhuyin: "ㄚ" },
    { word: "還", zhuyin: "ㄏㄞˊ" },
    { word: "漂", zhuyin: "ㄆㄧㄠˋ" },
    { word: "亮", zhuyin: "ㄌ一ㄤˋ" },
    { word: "顆", zhuyin: "ㄎㄜ" },
    { word: "蛋", zhuyin: "ㄉㄢˋ" },
    { word: "糕", zhuyin: "ㄍㄠ" },
    { word: "卡", zhuyin: "ㄎㄚˇ" },
    { word: "片", zhuyin: "ㄆㄧㄢˋ" },
    { word: "秋", zhuyin: "ㄑㄧㄡ" },
    { word: "採", zhuyin: "ㄘㄞˇ" },
    { word: "果", zhuyin: "ㄍㄨㄛˇ" },
    { word: "吃", zhuyin: "ㄔ" },
    { word: "飽", zhuyin: "ㄅㄠˇ" },
    { word: "方", zhuyin: "ㄈㄤ" },
    { word: "埋", zhuyin: "ㄇㄞˊ" },
    { word: "進", zhuyin: "ㄐㄧㄣˋ" },
    { word: "很", zhuyin: "ㄏㄣˇ" },
    { word: "久", zhuyin: "ㄐㄧㄡˋ" },
    { word: "嗎", zhuyin: "ㄇㄚ" },
    { word: "長", zhuyin: "ㄓㄤˇ" },
    { word: "敬", zhuyin: "ㄐㄧㄥˋ" },
    { word: "松", zhuyin: "ㄙㄨㄥ" },
    { word: "從", zhuyin: "ㄘㄨㄥˊ" },
    { word: "等", zhuyin: "ㄉㄥˇ" },
    { word: "奶", zhuyin: "ㄋㄞˇ" },
    { word: "貝", zhuyin: "ㄅㄟˋ" },
    { word: "早", zhuyin: "ㄗㄠˇ" },
    { word: "校", zhuyin: "ㄒㄧㄠˋ" },
    { word: "園", zhuyin: "ㄩㄢˊ" },
    { word: "工", zhuyin: "ㄍㄨㄥ" },
    { word: "作", zhuyin: "ㄗㄨㄛˋ" },
    { word: "她", zhuyin: "ㄊㄚ" },
    { word: "邊", zhuyin: "ㄅㄧㄢ" },
    { word: "汗", zhuyin: "ㄏㄢˋ" },
    { word: "學", zhuyin: "ㄒㄩㄝˊ" },
    { word: "您", zhuyin: "ㄋㄧㄣˊ" },
    { word: "樣", zhuyin: "ㄧㄤˋ" },
    { word: "當", zhuyin: "ㄉㄤ" },
    { word: "成", zhuyin: "ㄔㄥˊ" },
    { word: "寶", zhuyin: "ㄅㄠˇ" },
    { word: "擦", zhuyin: "ㄘㄚ" },
    { word: "澆", zhuyin: "ㄐㄧㄠ" },
    { word: "井", zhuyin: "ㄐㄧㄥˇ" },
    { word: "隻", zhuyin: "ㄓ" },
    { word: "除", zhuyin: "ㄔㄨˊ" },
    { word: "睡", zhuyin: "ㄕㄨㄟˋ" },
    { word: "覺", zhuyin: "ㄐㄧㄠˊ" },
    { word: "師", zhuyin: "ㄕ" },
    { word: "鼠", zhuyin: "ㄕㄨˇ" },
    { word: "東", zhuyin: "ㄉㄨㄥ" },
    { word: "西", zhuyin: "ㄒㄧ" },
    { word: "拍", zhuyin: "ㄆㄞ" },
    { word: "肚", zhuyin: "ㄉㄨˋ" },
    { word: "唉", zhuyin: "ㄞ" },
    { word: "幾", zhuyin: "ㄐㄧˇ" },
    { word: "世", zhuyin: "ㄕˋ" },
    { word: "界", zhuyin: "ㄐㄧㄝˋ" },
    { word: "連", zhuyin: "ㄌㄧㄢˊ" },
    { word: "裝", zhuyin: "ㄓㄨㄤ" },
    { word: "蛙", zhuyin: "ㄨㄚ" },
    { word: "窪", zhuyin: "ㄨㄚ" },
    { word: "星", zhuyin: "ㄒㄧㄥ" },
    { word: "面", zhuyin: "ㄇㄧㄢˋ" },
    { word: "許", zhuyin: "ㄒㄩˇ" },
    { word: "池", zhuyin: "ㄔˊ" },
    { word: "圈", zhuyin: "ㄑㄩㄢ" },
    { word: "波", zhuyin: "ㄅㄛ" },
    { word: "紋", zhuyin: "ㄨㄣˊ" },
    { word: "見", zhuyin: "ㄐㄧㄢˋ" },
    { word: "快", zhuyin: "ㄎㄨㄞˋ" },
    { word: "告", zhuyin: "ㄍㄠˋ" },
    { word: "訴", zhuyin: "ㄙㄨˋ" },
    { word: "光", zhuyin: "ㄍㄨㄤ" },
    { word: "拉", zhuyin: "ㄌㄚ" },
    { word: "怪", zhuyin: "ㄍㄨㄞˋ" },
    { word: "呀", zhuyin: "ㄧㄚ" },
    { word: "鴨", zhuyin: "ㄧㄚ" },
    { word: "塘", zhuyin: "ㄊㄤˊ" },
    { word: "止", zhuyin: "ㄓˇ" },
    { word: "半", zhuyin: "ㄅㄢˋ" },
    { word: "羊", zhuyin: "ㄧㄤˊ" },
    { word: "田", zhuyin: "ㄊㄧㄢˊ" },
    { word: "再", zhuyin: "ㄗㄞˋ" },
    { word: "瓜", zhuyin: "ㄍㄨㄚ" },
    { word: "苗", zhuyin: "ㄇㄧㄠˊ" },
    { word: "辛", zhuyin: "ㄒㄧㄣ" },
    { word: "苦", zhuyin: "ㄎㄨˇ" },
    { word: "油", zhuyin: "ㄧㄡˊ" },
    { word: "能", zhuyin: "ㄋㄥˊ" },
    { word: "收", zhuyin: "ㄕㄡ" },
    { word: "甜", zhuyin: "ㄊㄧㄢˊ" },
    { word: "分", zhuyin: "ㄈㄣ" },
    { word: "享", zhuyin: "ㄒㄧㄤˇ" },
    { word: "豬", zhuyin: "ㄓㄨ" },
    { word: "種", zhuyin: "ㄓㄨㄥˇ" },
    { word: "葉", zhuyin: "ㄧㄝˋ" }





    ],

    3: [
    { word: "呼", zhuyin: "ㄏㄨ" },
    { word: "白", zhuyin: "ㄅㄞˊ" },
    { word: "雲", zhuyin: "ㄩㄣˊ" },
    { word: "柔", zhuyin: "ㄖㄡˊ" },
    { word: "前", zhuyin: "ㄑㄧㄢˊ" },
    { word: "游", zhuyin: "ㄧㄡˊ" },
    { word: "噴", zhuyin: "ㄆㄣ" },
    { word: "美", zhuyin: "ㄇㄟˇ" },
    { word: "麗", zhuyin: "ㄌㄧˋ" },
    { word: "柱", zhuyin: "ㄓㄨˋ" },
    { word: "試", zhuyin: "ㄕˋ" },
    { word: "吸", zhuyin: "ㄒㄧ" },
    { word: "用", zhuyin: "ㄩㄥˋ" },
    { word: "力", zhuyin: "ㄌㄧˋ" },
    { word: "哇", zhuyin: "ㄨㄚ" },
    { word: "又", zhuyin: "ㄧㄡˋ" },
    { word: "第", zhuyin: "ㄉㄧˋ" },
    { word: "功", zhuyin: "ㄍㄨㄥ" },
    { word: "擠", zhuyin: "ㄐㄧˇ" },
    { word: "爬", zhuyin: "ㄆㄚˊ" },
    { word: "梯", zhuyin: "ㄊㄧ" },
    { word: "紙", zhuyin: "ㄓˇ" },
    { word: "條", zhuyin: "ㄊㄧㄠˊ" },
    { word: "線", zhuyin: "ㄒㄧㄢˋ" },
    { word: "像", zhuyin: "ㄒㄧㄤˋ" },
    { word: "身", zhuyin: "ㄕㄣ" },
    { word: "生", zhuyin: "ㄕㄥ" },
    { word: "迫", zhuyin: "ㄆㄛˋ" },
    { word: "及", zhuyin: "ㄐㄧˊ" },
    { word: "待", zhuyin: "ㄉㄞˋ" },
    { word: "站", zhuyin: "ㄓㄢˋ" },
    { word: "沿", zhuyin: "ㄧㄢˊ" },
    { word: "頂", zhuyin: "ㄉㄧㄥˇ" },
    { word: "格", zhuyin: "ㄍㄜˊ" },
    { word: "哪", zhuyin: "ㄋㄚˇ" },
    { word: "才", zhuyin: "ㄘㄞˊ" },
    { word: "最", zhuyin: "ㄗㄨㄟˋ" },
    { word: "勇", zhuyin: "ㄩㄥˇ" },
    { word: "教", zhuyin: "ㄐㄧㄠˋ" },
    { word: "室", zhuyin: "ㄕˋ" },
    { word: "棵", zhuyin: "ㄎㄜ" },
    { word: "葉", zhuyin: "ㄧㄝˋ" },
    { word: "克", zhuyin: "ㄎㄜˋ" },
    { word: "服", zhuyin: "ㄈㄨˊ" },
    { word: "害", zhuyin: "ㄏㄞˋ" },
    { word: "怕", zhuyin: "ㄆㄚˋ" },
    { word: "努", zhuyin: "ㄋㄨˇ" },
    { word: "完", zhuyin: "ㄨㄢˊ" },
    { word: "事", zhuyin: "ㄕˋ" },
    { word: "倒", zhuyin: "ㄉㄠˋ" },
    { word: "時", zhuyin: "ㄕˊ" },
    { word: "黑", zhuyin: "ㄏㄟ" },
    { word: "低", zhuyin: "ㄉㄧ" },
    { word: "聲", zhuyin: "ㄕㄥ" },
    { word: "故", zhuyin: "ㄍㄨˋ" },
    { word: "跌", zhuyin: "ㄉㄧㄝ" },
    { word: "騎", zhuyin: "ㄑㄧˊ" },
    { word: "塊", zhuyin: "ㄎㄨㄞˋ" },
    { word: "圓", zhuyin: "ㄩㄢˊ" },
    { word: "形", zhuyin: "ㄒㄧㄥˊ" },
    { word: "芝", zhuyin: "ㄓ" },
    { word: "麻", zhuyin: "ㄇㄚˊ" },
    { word: "餅", zhuyin: "ㄅㄧㄥˇ" },
    { word: "咬", zhuyin: "ㄧㄠˇ" },
    { word: "飯", zhuyin: "ㄈㄢˋ" },
    { word: "做", zhuyin: "ㄗㄨㄛˋ" },
    { word: "課", zhuyin: "ㄎㄜˋ" },
    { word: "洗", zhuyin: "ㄒㄧˇ" },
    { word: "澡", zhuyin: "ㄗㄠˇ" },
    { word: "拾", zhuyin: "ㄕˊ" },
    { word: "整", zhuyin: "ㄓㄥˇ" },
    { word: "包", zhuyin: "ㄅㄠ" },
    { word: "遊", zhuyin: "ㄧㄡˊ" },
    { word: "戲", zhuyin: "ㄒㄧˋ" },
    { word: "剩", zhuyin: "ㄕㄥˋ" },
    { word: "蟲", zhuyin: "ㄔㄨㄥˊ" },
    { word: "森", zhuyin: "ㄙㄣ" },
    { word: "動", zhuyin: "ㄉㄨㄥˋ" },
    { word: "物", zhuyin: "ㄨˋ" },
    { word: "王", zhuyin: "ㄨㄤˊ" },
    { word: "坐", zhuyin: "ㄗㄨㄛˋ" },
    { word: "午", zhuyin: "ㄨˇ" },
    { word: "停", zhuyin: "ㄊㄧㄥˊ" },
    { word: "座", zhuyin: "ㄗㄨㄛˋ" },
    { word: "橋", zhuyin: "ㄑㄧㄠˊ" },
    { word: "急", zhuyin: "ㄐㄧˊ" },
    { word: "原", zhuyin: "ㄩㄢˊ" },
    { word: "從", zhuyin: "ㄘㄨㄥˊ" },
    { word: "此", zhuyin: "ㄘˇ" },
    { word: "管", zhuyin: "ㄍㄨㄢˇ" },
    { word: "百", zhuyin: "ㄅㄞˇ" },
    { word: "科", zhuyin: "ㄎㄜ" },
    { word: "全", zhuyin: "ㄑㄩㄢˊ" },
    { word: "圖", zhuyin: "ㄊㄨˊ" },
    { word: "館", zhuyin: "ㄍㄨㄢˇ" },
    { word: "自", zhuyin: "ㄗˋ" },
    { word: "己", zhuyin: "ㄐㄧˇ" },
    { word: "沙", zhuyin: "ㄕㄚ" },
    { word: "撿", zhuyin: "ㄐㄧㄢˇ" },
    { word: "垃", zhuyin: "ㄌㄚ" },
    { word: "圾", zhuyin: "ㄐㄧ" },
    { word: "眼", zhuyin: "ㄧㄢˇ" },
    { word: "膠", zhuyin: "ㄐㄧㄠ" },
    { word: "對", zhuyin: "ㄉㄨㄟˋ" },
    { word: "牠", zhuyin: "ㄊㄚ" },
    { word: "安", zhuyin: "ㄢ" },
    { word: "吧", zhuyin: "ㄅㄚ" },
    { word: "如", zhuyin: "ㄖㄨˊ" },
    { word: "該", zhuyin: "ㄍㄞ" },
    { word: "留", zhuyin: "ㄌㄧㄡˊ" },
    { word: "便", zhuyin: "ㄅㄧㄢˋ" },
    { word: "減", zhuyin: "ㄐㄧㄢˇ" },
    { word: "少", zhuyin: "ㄕㄠˇ" },
    { word: "灘", zhuyin: "ㄊㄢ" },
    { word: "塑", zhuyin: "ㄙㄨˋ" },
    { word: "等", zhuyin: "ㄉㄥˇ" },
    { word: "兔", zhuyin: "ㄊㄨˋ" },
    { word: "農", zhuyin: "ㄋㄨㄥˊ" },
    { word: "夫", zhuyin: "ㄈㄨ" },
    { word: "種", zhuyin: "ㄓㄨㄥˇ" },
    { word: "夏", zhuyin: "ㄒㄧㄚˋ" },
    { word: "剛", zhuyin: "ㄍㄤ" },
    { word: "趕", zhuyin: "ㄍㄢˇ" },
    { word: "路", zhuyin: "ㄌㄨˋ" },
    { word: "幸", zhuyin: "ㄒㄧㄥˋ" },
    { word: "運", zhuyin: "ㄩㄣˋ" },
    { word: "以", zhuyin: "ㄧˇ" },
    { word: "耕", zhuyin: "ㄍㄥ" },
    { word: "守", zhuyin: "ㄕㄡˇ" },
    { word: "夜", zhuyin: "ㄧㄝˋ" },
    { word: "晚", zhuyin: "ㄨㄢˇ" },
    { word: "北", zhuyin: "ㄅㄟˇ" },
    { word: "搖", zhuyin: "ㄧㄠˊ" },
    { word: "撞", zhuyin: "ㄓㄨㄤˋ" },
    { word: "角", zhuyin: "ㄐㄧㄠˇ" },
    { word: "腳", zhuyin: "ㄐㄧㄠˇ" },
    { word: "渴", zhuyin: "ㄎㄜˇ" },
    { word: "鹿", zhuyin: "ㄌㄨˋ" },
    { word: "喝", zhuyin: "ㄏㄜ" },
    { word: "影", zhuyin: "ㄧㄥˇ" },
    { word: "意", zhuyin: "ㄧˋ" },
    { word: "卻", zhuyin: "ㄑㄩㄝˋ" },
    { word: "獅", zhuyin: "ㄕ" },
    { word: "追", zhuyin: "ㄓㄨㄟ" },
    { word: "被", zhuyin: "ㄅㄟˋ" },
    { word: "枝", zhuyin: "ㄓ" },
    { word: "掙", zhuyin: "ㄓㄥ" },
    { word: "脫", zhuyin: "ㄊㄨㄛ" },
    { word: "速", zhuyin: "ㄙㄨˋ" },
    { word: "度", zhuyin: "ㄉㄨˋ" },
    { word: "直", zhuyin: "ㄓˊ" },
    { word: "救", zhuyin: "ㄐㄧㄡˋ" },
    { word: "瘦", zhuyin: "ㄕㄡˋ" },
    { word: "嚇", zhuyin: "ㄒㄧㄚˋ" },
    { word: "赤", zhuyin: "ㄔˋ" },
    { word: "國", zhuyin: "ㄍㄨㄛˊ" },
    { word: "熱", zhuyin: "ㄖㄜˋ" },
    { word: "宮", zhuyin: "ㄍㄨㄥ" },
    { word: "涼", zhuyin: "ㄌㄧㄤˊ" },
    { word: "踩", zhuyin: "ㄘㄞˇ" },
    { word: "毯", zhuyin: "ㄊㄢˇ" },
    { word: "暖", zhuyin: "ㄋㄨㄢˇ" },
    { word: "馬", zhuyin: "ㄇㄚˇ" },
    { word: "壞", zhuyin: "ㄏㄨㄞˋ" },
    { word: "難", zhuyin: "ㄋㄢˊ" },
    { word: "定", zhuyin: "ㄉㄧㄥˋ" },
    { word: "更", zhuyin: "ㄍㄥ" },
    { word: "隨", zhuyin: "ㄙㄨㄟˊ" },
    { word: "主", zhuyin: "ㄓㄨˇ" },
    { word: "法", zhuyin: "ㄈㄚˇ" },
    { word: "於", zhuyin: "ㄩˊ" },
    { word: "舒", zhuyin: "ㄕㄨ" },
    { word: "燙", zhuyin: "ㄊㄤˋ" },
    { word: "蹺", zhuyin: "ㄑㄧㄠ" },
    { word: "群", zhuyin: "ㄑㄩㄣˊ" },
    { word: "靜", zhuyin: "ㄐㄧㄥˋ" },
    { word: "抬", zhuyin: "ㄊㄞˊ" },
    { word: "非", zhuyin: "ㄈㄟ" },
    { word: "趣", zhuyin: "ㄑㄩˋ" },
    { word: "近", zhuyin: "ㄐㄧㄣˋ" },
    { word: "堆", zhuyin: "ㄉㄨㄟ" },
    { word: "棉", zhuyin: "ㄇㄧㄢˊ" },
    { word: "遠", zhuyin: "ㄩㄢˇ" },
    { word: "景", zhuyin: "ㄐㄧㄥˇ" },
    { word: "忽", zhuyin: "ㄏㄨ" },
    { word: "聽", zhuyin: "ㄊㄧㄥ" },
    { word: "揮", zhuyin: "ㄏㄨㄟ" },
    { word: "慢", zhuyin: "ㄇㄢˋ" },
    { word: "依", zhuyin: "ㄧ" },
    { word: "捨", zhuyin: "ㄕㄜˇ" },
    { word: "放", zhuyin: "ㄈㄤˋ" },
    { word: "假", zhuyin: "ㄐㄧㄚˋ" },
    { word: "湯", zhuyin: "ㄊㄤ" },
    { word: "今", zhuyin: "ㄐㄧㄣ" },
    { word: "至", zhuyin: "ㄓˋ" },
    { word: "妹", zhuyin: "ㄇㄟˋ" },
    { word: "升", zhuyin: "ㄕㄥ" },
    { word: "陽", zhuyin: "ㄧㄤˊ" },
    { word: "因", zhuyin: "ㄧㄣ" },
    { word: "期", zhuyin: "ㄑㄧ" },
    { word: "盯", zhuyin: "ㄉㄧㄥ" },
    { word: "米", zhuyin: "ㄇㄧˇ" },
    { word: "團", zhuyin: "ㄊㄨㄢˊ" },
    { word: "粉", zhuyin: "ㄈㄣˇ" },
    { word: "南", zhuyin: "ㄋㄢˊ" },
    { word: "黃", zhuyin: "ㄏㄨㄤˊ" },
    { word: "真", zhuyin: "ㄓㄣ" },
    { word: "呵", zhuyin: "ㄏㄜ" },
    { word: "接", zhuyin: "ㄐㄧㄝ" },
    { word: "牛", zhuyin: "ㄋㄧㄡˊ" },
    { word: "糯", zhuyin: "ㄋㄨㄛˋ" },
    { word: "變", zhuyin: "ㄅㄧㄢˋ" },
    { word: "野", zhuyin: "ㄧㄝˇ" },
    { word: "本", zhuyin: "ㄅㄣˇ" },
    { word: "模", zhuyin: "ㄇㄛˊ" },
    { word: "型", zhuyin: "ㄒㄧㄥˊ" },
    { word: "蜜", zhuyin: "ㄇㄧˋ" },
    { word: "蜂", zhuyin: "ㄈㄥ" },
    { word: "蝴", zhuyin: "ㄏㄨˊ" },
    { word: "蝶", zhuyin: "ㄉㄧㄝˊ" },
    { word: "飛", zhuyin: "ㄈㄟ" },
    { word: "活", zhuyin: "ㄏㄨㄛˊ" },
    { word: "圖", zhuyin: "ㄊㄨˊ" },
    { word: "筆", zhuyin: "ㄅㄧˇ" },
    { word: "料", zhuyin: "ㄌㄧㄠˋ" },
    { word: "湖", zhuyin: "ㄏㄨˊ" },
    { word: "調", zhuyin: "ㄉㄧㄠˋ" },
    { word: "迷", zhuyin: "ㄇㄧˊ" },
    { word: "逛", zhuyin: "ㄍㄨㄤˋ" },
    { word: "兒", zhuyin: "ㄦˊ" },
    { word: "盤", zhuyin: "ㄆㄢˊ" }
    ],

    4: [
    { word: "情", zhuyin: "ㄑㄧㄥˊ" },
    { word: "候", zhuyin: "ㄏㄡˋ" },
    { word: "翠", zhuyin: "ㄘㄨㄟˋ" },
    { word: "溜", zhuyin: "ㄌㄧㄡ" },
    { word: "滑", zhuyin: "ㄏㄨㄚˊ" },
    { word: "傳", zhuyin: "ㄔㄨㄢˊ" },
    { word: "深", zhuyin: "ㄕㄣ" },
    { word: "泳", zhuyin: "ㄩㄥˇ" },
    { word: "淚", zhuyin: "ㄌㄟˋ" },
    { word: "火", zhuyin: "ㄏㄨㄛˇ" },
    { word: "奔", zhuyin: "ㄅㄣ" },
    { word: "怒", zhuyin: "ㄋㄨˋ" },
    { word: "拋", zhuyin: "ㄆㄠ" },
    { word: "潔", zhuyin: "ㄐㄧㄝˊ" },
    { word: "舞", zhuyin: "ㄨˇ" },
    { word: "各", zhuyin: "ㄍㄜˋ" },
    { word: "同", zhuyin: "ㄊㄨㄥˊ" },
    { word: "受", zhuyin: "ㄕㄡˋ" },
    { word: "藏", zhuyin: "ㄘㄤˊ" },
    { word: "敢", zhuyin: "ㄍㄢˇ" },
    { word: "超", zhuyin: "ㄔㄠ" },
    { word: "弟", zhuyin: "ㄉㄧˋ" },
    { word: "院", zhuyin: "ㄩㄢˋ" },
    { word: "正", zhuyin: "ㄓㄥˋ" },
    { word: "破", zhuyin: "ㄆㄛˋ" },
    { word: "所", zhuyin: "ㄙㄨㄛˇ" },
    { word: "伸", zhuyin: "ㄕㄣ" },
    { word: "點", zhuyin: "ㄉㄧㄢˇ" },
    { word: "重", zhuyin: "ㄓㄨㄥˋ" },
    { word: "石", zhuyin: "ㄕˊ" },
    { word: "消", zhuyin: "ㄒㄧㄠ" },
    { word: "失", zhuyin: "ㄕ" },
    { word: "合", zhuyin: "ㄏㄜˊ" },
    { word: "掉", zhuyin: "ㄉㄧㄠˋ" },
    { word: "乾", zhuyin: "ㄍㄢ" },
    { word: "淨", zhuyin: "ㄐㄧㄥˋ" },
    { word: "哥", zhuyin: "ㄍㄜ" },
    { word: "盆", zhuyin: "ㄆㄣˊ" },
    { word: "綿", zhuyin: "ㄇㄧㄢˊ" },
    { word: "已", zhuyin: "ㄧˇ" },
    { word: "經", zhuyin: "ㄐㄧㄥ" },
    { word: "輸", zhuyin: "ㄕㄨ" },
    { word: "鼓", zhuyin: "ㄍㄨˇ" },
    { word: "取", zhuyin: "ㄑㄩˇ" },
    { word: "越", zhuyin: "ㄩㄝˋ" },
    { word: "竟", zhuyin: "ㄐㄧㄥˋ" },
    { word: "飄", zhuyin: "ㄆㄧㄠ" },
    { word: "抓", zhuyin: "ㄓㄨㄚ" },
    { word: "啦", zhuyin: "ㄌㄚ" },
    { word: "喊", zhuyin: "ㄏㄢˇ" },
    { word: "踢", zhuyin: "ㄊㄧ" },
    { word: "結", zhuyin: "ㄐㄧㄝˊ" },
    { word: "變", zhuyin: "ㄅㄧㄢˋ" },
    { word: "讓", zhuyin: "ㄖㄤˋ" },
    { word: "終", zhuyin: "ㄓㄨㄥ" },
    { word: "冷", zhuyin: "ㄌㄥˇ" },
    { word: "亂", zhuyin: "ㄌㄨㄢˋ" },
    { word: "脾", zhuyin: "ㄆㄧˊ" },
    { word: "珠", zhuyin: "ㄓㄨ" },
    { word: "微", zhuyin: "ㄨㄟ" },
    { word: "醒", zhuyin: "ㄒㄧㄥˇ" },
    { word: "甲", zhuyin: "ㄐㄧㄚˇ" },
    { word: "瓢", zhuyin: "ㄆㄧㄠˊ" },
    { word: "腰", zhuyin: "ㄧㄠ" },
    { word: "香", zhuyin: "ㄒㄧㄤ" },
    { word: "掛", zhuyin: "ㄍㄨㄚˋ" },
    { word: "閃", zhuyin: "ㄕㄢˇ" },
    { word: "晶", zhuyin: "ㄐㄧㄥ" },
    { word: "串", zhuyin: "ㄔㄨㄢˋ" },
    { word: "項", zhuyin: "ㄒㄧㄤˋ" },
    { word: "鍊", zhuyin: "ㄌㄧㄢˋ" },
    { word: "仙", zhuyin: "ㄒㄧㄢ" },
    { word: "禮", zhuyin: "ㄌㄧˇ" },
    { word: "探", zhuyin: "ㄊㄢ" },
    { word: "幫", zhuyin: "ㄅㄤ" },
    { word: "姐", zhuyin: "ㄐㄧㄝˇ" },
    { word: "懶", zhuyin: "ㄌㄢˇ" },
    { word: "滾", zhuyin: "ㄍㄨㄣˇ" },
    { word: "病", zhuyin: "ㄅㄧㄥˋ" },
    { word: "睛", zhuyin: "ㄐㄧㄥ" },
    { word: "份", zhuyin: "ㄈㄣˋ" },
    { word: "牽", zhuyin: "ㄑㄧㄢ" },
    { word: "步", zhuyin: "ㄅㄨˋ" },
    { word: "段", zhuyin: "ㄉㄨㄢˋ" },
    { word: "毛", zhuyin: "ㄇㄠˊ" },
    { word: "晃", zhuyin: "ㄏㄨㄤˇ" },
    { word: "籃", zhuyin: "ㄌㄢˊ" },
    { word: "亭", zhuyin: "ㄊㄧㄥˊ" },
    { word: "忍", zhuyin: "ㄖㄣˇ" },
    { word: "祕", zhuyin: "ㄇㄧˋ" },
    { word: "耳", zhuyin: "ㄦˇ" },
    { word: "聞", zhuyin: "ㄨㄣˊ" },
    { word: "味", zhuyin: "ㄨㄟˋ" },
    { word: "浪", zhuyin: "ㄌㄤˋ" },
    { word: "寶", zhuyin: "ㄅㄠˇ" },
    { word: "清", zhuyin: "ㄑㄧㄥ" },
    { word: "封", zhuyin: "ㄈㄥ" },
    { word: "信", zhuyin: "ㄒㄧㄣˋ" },
    { word: "親", zhuyin: "ㄑㄧㄣ" },
    { word: "貴", zhuyin: "ㄍㄨㄟˋ" },
    { word: "洋", zhuyin: "ㄧㄤˊ" },
    { word: "蝦", zhuyin: "ㄒㄧㄚ" },
    { word: "植", zhuyin: "ㄓˊ" },
    { word: "量", zhuyin: "ㄌㄧㄤˋ" },
    { word: "汙", zhuyin: "ㄨ" },
    { word: "染", zhuyin: "ㄖㄢˇ" },
    { word: "使", zhuyin: "ㄕˇ" },
    { word: "決", zhuyin: "ㄐㄩㄝˊ" },
    { word: "具", zhuyin: "ㄐㄩˋ" },
    { word: "資", zhuyin: "ㄗ" },
    { word: "源", zhuyin: "ㄩㄢˊ" },
    { word: "費", zhuyin: "ㄈㄟˋ" },
    { word: "康", zhuyin: "ㄎㄤ" },
    { word: "復", zhuyin: "ㄈㄨˋ" },
    { word: "餐", zhuyin: "ㄘㄢ" },
    { word: "傘", zhuyin: "ㄙㄢˇ" },
    { word: "烏", zhuyin: "ㄨ" },
    { word: "暗", zhuyin: "ㄢˋ" },
    { word: "爺", zhuyin: "ㄧㄝˊ" },
    { word: "字", zhuyin: "ㄗˋ" },
    { word: "謎", zhuyin: "ㄇㄧˊ" },
    { word: "語", zhuyin: "ㄩˇ" },
    { word: "屋", zhuyin: "ㄨ" },
    { word: "枴", zhuyin: "ㄍㄨㄚˇ" },
    { word: "杖", zhuyin: "ㄓㄤˋ" },
    { word: "滴", zhuyin: "ㄉㄧ" },
    { word: "答", zhuyin: "ㄉㄚˊ" },
    { word: "叩", zhuyin: "ㄎㄡˋ" },
    { word: "嘻", zhuyin: "ㄒㄧ" },
    { word: "哈", zhuyin: "ㄏㄚ" },
    { word: "落", zhuyin: "ㄌㄨㄛˋ" },
    { word: "街", zhuyin: "ㄐㄧㄝ" },
    { word: "案", zhuyin: "ㄢˋ" },
    { word: "撐", zhuyin: "ㄔㄥ" },
    { word: "丁", zhuyin: "ㄉㄧㄥ" },
    { word: "公", zhuyin: "ㄍㄨㄥ" },
    { word: "每", zhuyin: "ㄇㄟˇ" },
    { word: "認", zhuyin: "ㄖㄣˋ" },
    { word: "比", zhuyin: "ㄅㄧˇ" },
    { word: "客", zhuyin: "ㄎㄜˋ" },
    { word: "相", zhuyin: "ㄒㄧㄤ" },
    { word: "興", zhuyin: "ㄒㄧㄥ" },
    { word: "照", zhuyin: "ㄓㄠˋ" },
    { word: "皮", zhuyin: "ㄆㄧˊ" },
    { word: "摘", zhuyin: "ㄓㄞ" },
    { word: "立", zhuyin: "ㄌㄧˋ" },
    { word: "位", zhuyin: "ㄨㄟˋ" },
    { word: "新", zhuyin: "ㄒㄧㄣ" },
    { word: "它", zhuyin: "ㄊㄚ" },
    { word: "欣", zhuyin: "ㄒㄧㄣ" },
    { word: "賞", zhuyin: "ㄕㄤˇ" },
    { word: "妙", zhuyin: "ㄇㄧㄠˋ" },
    { word: "牌", zhuyin: "ㄆㄞˊ" },
    { word: "排", zhuyin: "ㄆㄞˊ" },
    { word: "介", zhuyin: "ㄐㄧㄝˋ" },
    { word: "紹", zhuyin: "ㄕㄠˋ" },
    { word: "其", zhuyin: "ㄑㄧˊ" },
    { word: "賣", zhuyin: "ㄇㄞˋ" },
    { word: "帽", zhuyin: "ㄇㄠˋ" },
    { word: "蛋", zhuyin: "ㄉㄢˋ" },
    { word: "糕", zhuyin: "ㄍㄠ" },
    { word: "扶", zhuyin: "ㄈㄨˊ" },
    { word: "買", zhuyin: "ㄇㄞˇ" },
    { word: "休", zhuyin: "ㄒㄧㄡ" },
    { word: "息", zhuyin: "ㄒㄧ" },
    { word: "拿", zhuyin: "ㄋㄚˊ" },
    { word: "精", zhuyin: "ㄐㄧㄥ" },
    { word: "采", zhuyin: "ㄘㄞˇ" },
    { word: "希", zhuyin: "ㄒㄧ" },
    { word: "望", zhuyin: "ㄨㄤˋ" },
    { word: "讀", zhuyin: "ㄉㄨˊ" },
    { word: "戴", zhuyin: "ㄉㄞˋ" },
    { word: "猴", zhuyin: "ㄏㄡˊ" },
    { word: "銀", zhuyin: "ㄧㄣˊ" },
    { word: "年", zhuyin: "ㄋㄧㄢˊ" },
    { word: "幼", zhuyin: "ㄧㄡˋ" },
    { word: "女", zhuyin: "ㄋㄩˇ" },
    { word: "願", zhuyin: "ㄩㄢˋ" },
    { word: "碰", zhuyin: "ㄆㄥˋ" },
    { word: "桌", zhuyin: "ㄓㄨㄛ" },
    { word: "椅", zhuyin: "ㄧˇ" },
    { word: "部", zhuyin: "ㄅㄨˋ" },
    { word: "食", zhuyin: "ㄕˊ" },
    { word: "刻", zhuyin: "ㄎㄜˋ" },
    { word: "純", zhuyin: "ㄔㄨㄣˊ" },
    { word: "求", zhuyin: "ㄑㄧㄡˊ" },
    { word: "並", zhuyin: "ㄅㄧㄥˋ" },
    { word: "切", zhuyin: "ㄑㄧㄝ" },
    { word: "狀", zhuyin: "ㄓㄨㄤˋ" },
    { word: "明", zhuyin: "ㄇㄧㄥˊ" },
    { word: "珍", zhuyin: "ㄓㄣ" },
    { word: "術", zhuyin: "ㄕㄨˋ" },
    { word: "敗", zhuyin: "ㄅㄞˋ" },
    { word: "操", zhuyin: "ㄘㄠ" },
    { word: "旁", zhuyin: "ㄆㄤˊ" },
    { word: "脖", zhuyin: "ㄅㄛˊ" },
    { word: "瞇", zhuyin: "ㄇㄧ" },
    { word: "密", zhuyin: "ㄇㄧˋ" },
    { word: "件", zhuyin: "ㄐㄧㄢˋ" },
    { word: "特", zhuyin: "ㄊㄜˋ" },
    { word: "別", zhuyin: "ㄅㄧㄝˊ" },
    { word: "唱", zhuyin: "ㄔㄤˋ" },
    { word: "歌", zhuyin: "ㄍㄜ" },
    { word: "練", zhuyin: "ㄌㄧㄢˋ" },
    { word: "習", zhuyin: "ㄒㄧˊ" },
    { word: "彈", zhuyin: "ㄊㄢˊ" },
    { word: "琴", zhuyin: "ㄑㄧㄣˊ" },
    { word: "講", zhuyin: "ㄐㄧㄤˇ" },
    { word: "論", zhuyin: "ㄌㄨㄣˋ" },
    { word: "颳", zhuyin: "ㄍㄨㄚ" },
    { word: "勵", zhuyin: "ㄌㄧˋ" },
    { word: "牆", zhuyin: "ㄑㄧㄤˊ" },
    { word: "壁", zhuyin: "ㄅㄧˋ" },
    { word: "窗", zhuyin: "ㄔㄨㄤ" },
    { word: "床", zhuyin: "ㄔㄨㄤˊ" },
    { word: "鋪", zhuyin: "ㄆㄨ" },
    { word: "錯", zhuyin: "ㄘㄨㄛˋ" },
    { word: "輪", zhuyin: "ㄌㄨㄣˊ" },
    { word: "搬", zhuyin: "ㄅㄢ" },
    { word: "冰", zhuyin: "ㄅㄧㄥ" },
    { word: "而", zhuyin: "ㄦˊ" },
    { word: "且", zhuyin: "ㄑㄧㄝˇ" },
    { word: "交", zhuyin: "ㄐㄧㄠ" },
    { word: "往", zhuyin: "ㄨㄤˇ" },
    { word: "顆", zhuyin: "ㄎㄜ" },
    { word: "鮮", zhuyin: "ㄒㄧㄢ" },
    { word: "汁", zhuyin: "ㄓ" },
    { word: "晨", zhuyin: "ㄔㄣˊ" },
    { word: "由", zhuyin: "ㄧㄡˊ" },
    { word: "極", zhuyin: "ㄐㄧˊ" },
    { word: "磚", zhuyin: "ㄓㄨㄢ" }
    ],
    
    5: [
    { word: "泥", zhuyin: "ㄋㄧˊ" },
    { word: "化", zhuyin: "ㄏㄨㄚˋ" },
    { word: "雀", zhuyin: "ㄑㄩㄝˋ" },
    { word: "輕", zhuyin: "ㄑㄧㄥ" },
    { word: "羽", zhuyin: "ㄩˇ" },
    { word: "衣", zhuyin: "ㄧ" },
    { word: "脆", zhuyin: "ㄘㄨㄟˋ" },
    { word: "髮", zhuyin: "ㄈㄚˇ" },
    { word: "處", zhuyin: "ㄔㄨˇ" },
    { word: "旅", zhuyin: "ㄌㄩˇ" },
    { word: "行", zhuyin: "ㄒㄧㄥˊ" },
    { word: "平", zhuyin: "ㄆㄧㄥˊ" },
    { word: "男", zhuyin: "ㄋㄢˊ" },
    { word: "朗", zhuyin: "ㄌㄤˇ" },
    { word: "足", zhuyin: "ㄗㄨˊ" },
    { word: "廊", zhuyin: "ㄌㄤˊ" },
    { word: "訂", zhuyin: "ㄉㄧㄥˋ" },
    { word: "班", zhuyin: "ㄅㄢ" },
    { word: "級", zhuyin: "ㄐㄧˊ" },
    { word: "約", zhuyin: "ㄩㄝ" },
    { word: "紛", zhuyin: "ㄈㄣ" },
    { word: "持", zhuyin: "ㄔˊ" },
    { word: "記", zhuyin: "ㄐㄧˋ" },
    { word: "錄", zhuyin: "ㄌㄨˋ" },
    { word: "聊", zhuyin: "ㄌㄧㄠˊ" },
    { word: "言", zhuyin: "ㄧㄢˊ" },
    { word: "烈", zhuyin: "ㄌㄧㄝˋ" },
    { word: "些", zhuyin: "ㄒㄧㄝ" },
    { word: "提", zhuyin: "ㄊㄧˊ" },
    { word: "愁", zhuyin: "ㄔㄡˊ" },
    { word: "短", zhuyin: "ㄉㄨㄢˇ" },
    { word: "鐘", zhuyin: "ㄓㄨㄥ" },
    { word: "鬼", zhuyin: "ㄍㄨㄟˇ" },
    { word: "鬧", zhuyin: "ㄋㄠˋ" },
    { word: "準", zhuyin: "ㄓㄨㄣˇ" },
    { word: "朝", zhuyin: "ㄔㄠˊ" },
    { word: "蹈", zhuyin: "ㄉㄠˋ" },
    { word: "表", zhuyin: "ㄅㄧㄠˇ" },
    { word: "暢", zhuyin: "ㄔㄤˋ" },
    { word: "無", zhuyin: "ㄨˊ" },
    { word: "總", zhuyin: "ㄗㄨㄥˇ" },
    { word: "響", zhuyin: "ㄒㄧㄤˇ" },
    { word: "忘", zhuyin: "ㄨㄤˋ" },
    { word: "盡", zhuyin: "ㄐㄧㄣˋ" },
    { word: "責", zhuyin: "ㄗㄜˊ" },
    { word: "指", zhuyin: "ㄓˇ" },
    { word: "夕", zhuyin: "ㄒㄧˋ" },
    { word: "賽", zhuyin: "ㄙㄞˋ" },
    { word: "緊", zhuyin: "ㄐㄧㄣˇ" },
    { word: "店", zhuyin: "ㄉㄧㄢˋ" },
    { word: "逗", zhuyin: "ㄉㄡˋ" },
    { word: "轉", zhuyin: "ㄓㄨㄢˇ" },
    { word: "露", zhuyin: "ㄌㄨˋ" },
    { word: "業", zhuyin: "ㄧㄝˋ" },
    { word: "專", zhuyin: "ㄓㄨㄢ" },
    { word: "勝", zhuyin: "ㄕㄥˋ" },
    { word: "利", zhuyin: "ㄌㄧˋ" },
    { word: "悅", zhuyin: "ㄩㄝˋ" },
    { word: "乖", zhuyin: "ㄍㄨㄞ" },
    { word: "溫", zhuyin: "ㄨㄣ" },
    { word: "龍", zhuyin: "ㄌㄨㄥˊ" },
    { word: "沖", zhuyin: "ㄔㄨㄥ" },
    { word: "菱", zhuyin: "ㄌㄧㄥˊ" },
    { word: "兄", zhuyin: "ㄒㄩㄥ" },
    { word: "吐", zhuyin: "ㄊㄨˋ" },
    { word: "歪", zhuyin: "ㄨㄞ" },
    { word: "防", zhuyin: "ㄈㄤˊ" },
    { word: "警", zhuyin: "ㄐㄧㄥˇ" },
    { word: "鈴", zhuyin: "ㄌㄧㄥˊ" },
    { word: "注", zhuyin: "ㄓㄨˋ" },
    { word: "員", zhuyin: "ㄩㄢˊ" },
    { word: "傷", zhuyin: "ㄕㄤ" },
    { word: "死", zhuyin: "ㄙˇ" },
    { word: "諒", zhuyin: "ㄌㄧㄤˋ" },
    { word: "脾", zhuyin: "ㄆㄧˊ" },
    { word: "幕", zhuyin: "ㄇㄨˋ" },
    { word: "杯", zhuyin: "ㄅㄟ" },
    { word: "撞", zhuyin: "ㄓㄨㄤˋ" },
    { word: "流", zhuyin: "ㄌㄧㄡˊ" },
    { word: "溼", zhuyin: "ㄕˉ" },
    { word: "透", zhuyin: "ㄊㄡˋ" },
    { word: "雙", zhuyin: "ㄕㄨㄤ" },
    { word: "胸", zhuyin: "ㄒㄧㄥ" },
    { word: "負", zhuyin: "ㄈㄨˋ" },
    { word: "慌", zhuyin: "ㄏㄨㄤ" },
    { word: "逃", zhuyin: "ㄊㄠˊ" },
    { word: "辦", zhuyin: "ㄅㄢˋ" },
    { word: "題", zhuyin: "ㄊㄧˊ" },
    { word: "灰", zhuyin: "ㄏㄨㄟ" },
    { word: "剪", zhuyin: "ㄐㄧㄢˇ" },
    { word: "背", zhuyin: "ㄅㄟˋ" },
    { word: "斑", zhuyin: "ㄅㄢ" },
    { word: "皺", zhuyin: "ㄓㄡˋ" },
    { word: "懂", zhuyin: "ㄉㄨㄥˇ" },
    { word: "凡", zhuyin: "ㄈㄢˊ" },
    { word: "梳", zhuyin: "ㄕㄨ" },
    { word: "夾", zhuyin: "ㄐㄧㄚˊ" },
    { word: "藏", zhuyin: "ㄘㄤˊ" },
    { word: "捏", zhuyin: "ㄋㄧㄝ" },
    { word: "摺", zhuyin: "ㄓㄜˊ" },
    { word: "仔", zhuyin: "ㄗˇ" },
    { word: "藝", zhuyin: "ㄧˋ" },
    { word: "術", zhuyin: "ㄕㄨˋ" },
    { word: "雖", zhuyin: "ㄙㄨㄟ" },
    { word: "創", zhuyin: "ㄔㄨㄤˋ" },
    { word: "魔", zhuyin: "ㄇㄛˊ" },
    { word: "圍", zhuyin: "ㄨㄟˊ" },
    { word: "巾", zhuyin: "ㄐㄧㄣ" },
    { word: "視", zhuyin: "ㄕˋ" },
    { word: "框", zhuyin: "ㄎㄨㄤ" },
    { word: "誤", zhuyin: "ㄨˋ" },
    { word: "愉", zhuyin: "ㄩˊ" },
    { word: "數", zhuyin: "ㄕㄨˋ" },
    { word: "桶", zhuyin: "ㄊㄨㄥˇ" },
    { word: "刀", zhuyin: "ㄉㄠ" },
    { word: "曾", zhuyin: "ㄗㄥ" },
    { word: "機", zhuyin: "ㄐㄧ" },
    { word: "解", zhuyin: "ㄐㄧㄝˇ" },
    { word: "鏡", zhuyin: "ㄐㄧㄥˋ" },
    { word: "齊", zhuyin: "ㄑㄧˊ" },
    { word: "醫", zhuyin: "ㄧ" },
    { word: "穿", zhuyin: "ㄔㄨㄢ" },
    { word: "袍", zhuyin: "ㄆㄠˊ" },
    { word: "戴", zhuyin: "ㄉㄞˋ" },
    { word: "筒", zhuyin: "ㄊㄨㄥˇ" },
    { word: "啄", zhuyin: "ㄓㄨㄛˊ" },
    { word: "備", zhuyin: "ㄅㄟˋ" },
    { word: "幹", zhuyin: "ㄍㄢˋ" },
    { word: "敲", zhuyin: "ㄑㄧㄠ" },
    { word: "毒", zhuyin: "ㄉㄨˊ" },
    { word: "體", zhuyin: "ㄊㄧˇ" },
    { word: "淘", zhuyin: "ㄊㄠˊ" },
    { word: "蘋", zhuyin: "ㄆㄧㄣˊ" },
    { word: "般", zhuyin: "ㄅㄢ" },
    { word: "藥", zhuyin: "ㄧㄠˋ" },
    { word: "極", zhuyin: "ㄐㄧˊ" },
    { word: "熊", zhuyin: "ㄒㄩㄥˊ" },
    { word: "雪", zhuyin: "ㄒㄩㄝˇ" },
    { word: "腦", zhuyin: "ㄋㄠˇ" },
    { word: "實", zhuyin: "ㄕˊ" },
    { word: "根", zhuyin: "ㄍㄣ" },
    { word: "反", zhuyin: "ㄈㄢˇ" },
    { word: "射", zhuyin: "ㄕㄜˋ" },
    { word: "膚", zhuyin: "ㄈㄨ" },
    { word: "豬", zhuyin: "ㄓㄨ" },
    { word: "呆", zhuyin: "ㄉㄞ" },
    { word: "印", zhuyin: "ㄧㄣˋ" },
    { word: "象", zhuyin: "ㄒㄧㄤˋ" },
    { word: "憶", zhuyin: "ㄧˋ" },
    { word: "滾", zhuyin: "ㄍㄨㄣˇ" },
    { word: "額", zhuyin: "ㄜˊ" },
    { word: "虎", zhuyin: "ㄏㄨˇ" },
    { word: "貓", zhuyin: "ㄇㄠ" },
    { word: "臺", zhuyin: "ㄊㄞˊ" },
    { word: "灣", zhuyin: "ㄨㄢ" },
    { word: "獨", zhuyin: "ㄉㄨˊ" },
    { word: "萬", zhuyin: "ㄨㄢˋ" },
    { word: "祖", zhuyin: "ㄗㄨˇ" },
    { word: "蛙", zhuyin: "ㄨㄚ" },
    { word: "捉", zhuyin: "ㄓㄨㄛ" },
    { word: "類", zhuyin: "ㄌㄟˋ" },
    { word: "占", zhuyin: "ㄓㄢˋ" },
    { word: "雞", zhuyin: "ㄐㄧ" },
    { word: "肉", zhuyin: "ㄖㄡˋ" },
    { word: "威", zhuyin: "ㄨㄟ" },
    { word: "昆", zhuyin: "ㄎㄨㄣ" },
    { word: "攻", zhuyin: "ㄍㄨㄥ" },
    { word: "擊", zhuyin: "ㄐㄧˊ" },
    { word: "演", zhuyin: "ㄧㄢˇ" },
    { word: "保", zhuyin: "ㄅㄠˇ" },
    { word: "命", zhuyin: "ㄇㄧㄥˋ" },
    { word: "翅", zhuyin: "ㄔˋ" },
    { word: "敵", zhuyin: "ㄉㄧˊ" },
    { word: "周", zhuyin: "ㄓㄡ" },
    { word: "竹", zhuyin: "ㄓㄨˊ" },
    { word: "節", zhuyin: "ㄐㄧㄝˊ" },
    { word: "逼", zhuyin: "ㄅㄧ" },
    { word: "技", zhuyin: "ㄐㄧˋ" },
    { word: "退", zhuyin: "ㄊㄨㄟˋ" },
    { word: "屁", zhuyin: "ㄆㄧˋ" }         
    ]
};

  let writer = null;
  let currentWord = "";
  let currentUtter = null;
  let mistakeCount = 0;

  // 初始化計數器
  function initCounter() {
    const today = new Date().toDateString();
    const savedDate = localStorage.getItem('counterDate');
    if (savedDate !== today) {
      localStorage.setItem('correctCount', '0');
      localStorage.setItem('counterDate', today);
    }
    updateCounterDisplay();
  }

  // 增加計數
  function incrementCounter() {
    let count = parseInt(localStorage.getItem('correctCount') || '0', 10);
    count += 1;
    localStorage.setItem('correctCount', count.toString());
    updateCounterDisplay();
  }

  // 更新顯示的計數
  function updateCounterDisplay() {
    const count = localStorage.getItem('correctCount') || '0';
    document.getElementById('counter').innerText = `✔️ 今天寫對：${count} 次`;
  }

  // 重播語音
  function replayAudio() {
    if (currentUtter) {
      speechSynthesis.cancel();
      speechSynthesis.speak(currentUtter);
    }
  }

  // 開始筆畫測驗
  function startQuiz() {
    mistakeCount = 0; // 每次新題目時重設

    writer.quiz({
      onMistake: () => {
        mistakeCount += 1;
        const msg = document.getElementById('message');

        if (mistakeCount === 2) {
          msg.innerText = '再錯一次就要重寫囉～';
        } else if (mistakeCount >= 3) {
          msg.innerText = '錯三次了，重新開始寫這個字！';
          mistakeCount = 0;

          // 清除舊的繪製狀態並重建
          const container = document.getElementById('hanzi-container');
          container.innerHTML = '';
          writer = HanziWriter.create(container, currentWord, {
            width: 300,
            height: 300,
            padding: 10,
            showOutline: true,
            showCharacter: false,
            strokeColor: '#000',
            radicalColor: '#000',
            drawingColor: '#000'
          });

          startQuiz(); // 重新開始 quiz
        } else {
          msg.innerText = '筆順錯了，請再試一次～';
        }

        // 自動清除錯誤訊息（不清除第 2 次提示）
        if (mistakeCount !== 2) {
          setTimeout(() => {
            msg.innerText = '';
          }, 700);
        }
      },

      onComplete: () => {
        document.getElementById('message').innerText = '寫對了！好棒！';
        incrementCounter();
      }
    });
  }

  // 載入隨機字元
  function loadRandomCharacter() {
    const grade = document.getElementById('grade-select').value;
    const chars = hanziData[grade];

    if (!chars || chars.length === 0) {
      alert("此年級尚未有字。");
      return;
    }

    const randomChar = chars[Math.floor(Math.random() * chars.length)];
    const { word, zhuyin } = randomChar;
    currentWord = word;

    document.getElementById('question').innerText = `請寫：「${word}」  注音：${zhuyin}`;
    document.getElementById('message').innerText = '';

    const container = document.getElementById('hanzi-container');
    container.innerHTML = ''; // 清除上一題的字形

    writer = HanziWriter.create(container, word, {
      width: 300,
      height: 300,
      padding: 10,
      showOutline: true,
      showCharacter: false,
      strokeColor: '#000',
      radicalColor: '#000',
      drawingColor: '#000'
    });

    startQuiz(); // 開始新的測驗

    // 自動播放語音
    currentUtter = new SpeechSynthesisUtterance(word);
    currentUtter.lang = 'zh-TW';
    currentUtter.rate = 0.8;
    speechSynthesis.cancel();
    speechSynthesis.speak(currentUtter);
  }

  // 頁面初始化
  window.onload = () => {
    initCounter();
    loadRandomCharacter();
  };