// JS
document.getElementById("nextBtn").addEventListener("click", nextCard);
document.getElementById("replayBtn").addEventListener("click", replay);

const words = [
 { "en": "dynamic", "zh": "有活力的,有生機的" },
{ "en": "prosperous", "zh": "繁榮的" },
{ "en": "brisk", "zh": "興隆的" },
{ "en": "volatile", "zh": "不穩定的, 活躍浮動的" },
{ "en": "bleak", "zh": "慘澹淒涼的" },
{ "en": "declining", "zh": "下滑的,衰退的" },
{ "en": "slump", "zh": "委靡的" },
{ "en": "sluggish", "zh": "不景氣,蕭條的" },
{ "en": "stagnant", "zh": "停滯不前的, 蕭條的" },
{ "en": "merchandise", "zh": "商品(集合名詞)(單數)" },
{ "en": "goods", "zh": "貨物(複)" },
{ "en": "commodity", "zh": "商品, 期貨 futures" },
{ "en": "product", "zh": "產品" },
{ "en": "produce", "zh": "農產品" },
{ "en": "freight", "zh": "運輸的貨物 ; 運費" },
{ "en": "cargo", "zh": "(船,飛機)裝載的貨物 convoke 召集" },
{ "en": "convoke", "zh": "召集" },
{ "en": "rally", "zh": "集合" },
{ "en": "gathering", "zh": "聚會" },
{ "en": "function", "zh": "集會，儀式 event" },
{ "en": "adjourn", "zh": "延會,休會" },
{ "en": "confer", "zh": "商談" },
{ "en": "mug", "zh": "搶劫,(從背後襲擊)" },
{ "en": "steal", "zh": "偷" },
{ "en": "loot", "zh": "搶奪" },
{ "en": "pickpocket", "zh": "扒手" },
{ "en": "burglary", "zh": "夜盜" },
{ "en": "smuggle", "zh": "走私" },
{ "en": "by cash", "zh": "現金" },
{ "en": "by check", "zh": "支票" },
{ "en": "by credit card", "zh": "信用卡" },
{ "en": "by money order", "zh": "匯票" },
{ "en": "by installment", "zh": "分期付款" },
{ "en": "by mail", "zh": "郵寄" },
{ "en": "outgoing", "zh": "外向活潑" },
{ "en": "sociable", "zh": "善於交際" },
{ "en": "adaptable", "zh": "適應性強" },
{ "en": "ambitious", "zh": "有野心" },
{ "en": "hard-working", "zh": "工作努力" },
{ "en": "energetic", "zh": "有活力" },
{ "en": "enterprising", "zh": "富於進取,有創業精神" },
{ "en": "honest", "zh": "誠實" },
{ "en": "reserved", "zh": "保守,穩重" },
{ "en": "responsible", "zh": "負責" },
{ "en": "optimistic", "zh": "樂觀" },
{ "en": "independent", "zh": "獨立" },
{ "en": "inflation", "zh": "通貨膨脹" },
{ "en": "deflation", "zh": "通貨緊縮" },
{ "en": "feasibility", "zh": "可行性" },
{ "en": "overhaul", "zh": "徹底檢查" },
{ "en": "custom", "zh": "海關" },
{ "en": "bruise", "zh": "擦傷" },
{ "en": "indices", "zh": "指數, 是 index 的複數" },
{ "en": "commotion", "zh": "暴動,騷亂" },
{ "en": "interest rate", "zh": "利率" },
{ "en": "disposition", "zh": "性情氣質,處理" },
{ "en": "carat, karat", "zh": "克拉" },
{ "en": "hallmark", "zh": "品質證明, 純正之證明" },
{ "en": "asylum", "zh": "收容所, 養老院" },
{ "en": "orphanage", "zh": "孤兒院" },
{ "en": "morale", "zh": "士氣,人心" },
{ "en": "pennant", "zh": "錦旗" },
{ "en": "vicinity", "zh": "附近, 短語是 in the ~ of" },
{ "en": "interrogation", "zh": "詢問,審訊 短語是 put sb under ~" },
{ "en": "intersection", "zh": "交點" },
{ "en": "intermission", "zh": "休息時間" },
{ "en": "physician", "zh": "內科醫生" },
{ "en": "surgeon", "zh": "外科醫生, 軍醫,船醫" },
{ "en": "breadwinner", "zh": "養家糊口的人" },
{ "en": "recipe", "zh": "食譜,方法" },
{ "en": "tender", "zh": "招標,a public ~, ask for tender" },
{ "en": "syllabus", "zh": "課程綱要" },
{ "en": "Spaniard", "zh": "西班牙人" },
{ "en": "dispassion", "zh": "冷靜客觀" },
{ "en": "levity", "zh": "輕率" },
{ "en": "expulsion", "zh": "開除,除籍" },
{ "en": "defamation", "zh": "誹謗" },
{ "en": "payroll", "zh": "薪水冊,工資表" },
{ "en": "contraction", "zh": "收縮" },
{ "en": "renewal", "zh": "更新" },
{ "en": "deduction", "zh": "扣除(額)" },
{ "en": "escalator", "zh": "電動扶梯" },
{ "en": "elevator", "zh": "電梯,升降梯(美)" },
{ "en": "lift", "zh": "電梯(英)" },
{ "en": "emblem", "zh": "象徵標誌 同 logo symbol" },
{ "en": "dereliction", "zh": "怠忽職守 ~ of duty" },
{ "en": "milk shake", "zh": "奶昔" },
{ "en": "endorsement", "zh": "背書保證,找明星代言" },
{ "en": "approbation", "zh": "批准許可" },
{ "en": "probation", "zh": "試用 trial" },
{ "en": "deference", "zh": "順從尊重" },
{ "en": "minor infraction", "zh": "輕微違法 major violation 重大" },
{ "en": "vacate", "zh": "疏散 evacuation" },
{ "en": "anarchy", "zh": "無政府" },
{ "en": "collusion", "zh": "共謀,勾結" },
{ "en": "downturn", "zh": "下滑 take a sudden downturn" },
{ "en": "spa", "zh": "溫泉" },
{ "en": "freelance writer", "zh": "自由撰稿人" },
{ "en": "articles", "zh": "用品,商品" },
{ "en": "management", "zh": "資方 union 工會" },
{ "en": "turnover", "zh": "運轉,周轉" },
{ "en": "turnout (", "zh": "集會)出席者 a large turnout" },
{ "en": "annuity", "zh": "養老金 =pension" },
{ "en": "extension", "zh": "分機" },
{ "en": "innovation", "zh": "革新翻新, renovation 裝修" },
{ "en": "dosage", "zh": "劑量" },
{ "en": "rash", "zh": "疹子" },
{ "en": "clientele", "zh": "顧客,老主顧" },
{ "en": "leave", "zh": "請假 He is often absent without leave" },
{ "en": "partition", "zh": "隔間,區分" },
{ "en": "junk", "zh": "垃圾" },
{ "en": "punk", "zh": "朋克" },
{ "en": "menopause", "zh": "更年期" },
{ "en": "razor", "zh": "剃刀" },
{ "en": "crop strains", "zh": "作物品種" },
{ "en": "headphone", "zh": "耳機" },
{ "en": "automated teller machine", "zh": "自動提款機 ATM" },
{ "en": "civilians", "zh": "平民（注意與 surveillance 區分）" },
{ "en": "subsidiary", "zh": "子公司" },
{ "en": "strip mining", "zh": "露天採礦" },
{ "en": "national", "zh": "國民（某國的）" },
{ "en": "mortgage", "zh": "抵押" },
{ "en": "compartment", "zh": "隔間" },
{ "en": "helping", "zh": "(食物的)一分" },
{ "en": "subcontractor", "zh": "轉包商" },
{ "en": "speculation", "zh": "投機" },
{ "en": "avocation", "zh": "副業" },
{ "en": "kickback", "zh": "回扣" },
{ "en": "spectator", "zh": "觀眾" },
{ "en": "stroller", "zh": "四輪嬰兒車，漫步者" },
{ "en": "seniority", "zh": "年長，資深" },
{ "en": "toner", "zh": "調色劑" },
{ "en": "luncheon", "zh": "正式午餐，下午餐會" },
{ "en": "façade", "zh": "建築物正面" },
{ "en": "decoy", "zh": "欺騙，引誘" },
{ "en": "interface", "zh": "交互介面" },
{ "en": "boutiques", "zh": "小店，精品店" },
{ "en": "casino", "zh": "俱樂部，遊樂場" },
{ "en": "complex", "zh": "整套設施" },
{ "en": "commencement ceremony", "zh": "授學位典禮" },
{ "en": "inception", "zh": "開始" },
{ "en": "induction", "zh": "入伍" },
{ "en": "modem", "zh": "數據機" },
{ "en": "fraud", "zh": "詐騙" },
{ "en": "magnate", "zh": "工業巨頭" },
{ "en": "gourmet", "zh": "美食家" },
{ "en": "ordinance", "zh": "法令" },
{ "en": "cursor", "zh": "游標" },
{ "en": "liaison", "zh": "交流合作" },
{ "en": "portfolio", "zh": "公事包，文件夾" },
{ "en": "corrosives", "zh": "易腐蝕品" },
{ "en": "corporation", "zh": "企業（注意與 cooperation 區分）" },
{ "en": "minute", "zh": "會議錄" },
{ "en": "recreation", "zh": "娛樂，休閒" },
{ "en": "strand", "zh": "使擱淺，陷入困境" },
{ "en": "relate", "zh": "敘述" },
{ "en": "facilitate", "zh": "使便利" },
{ "en": "excel", "zh": "優出勝出" },
{ "en": "exceed", "zh": "超過" },
{ "en": "remit", "zh": "匯款，寬恕" },
{ "en": "highlight", "zh": "強調" },
{ "en": "inoculate", "zh": "接種" },
{ "en": "vaccinate", "zh": "接種疫苗" },
{ "en": "remedy", "zh": "補救" },
{ "en": "undermine", "zh": "詆毀" },
{ "en": "reverse", "zh": "顛倒" },
{ "en": "slam", "zh": "使勁關" },
{ "en": "equip", "zh": "配備" },
{ "en": "capsize", "zh": "傾覆（船）" },
{ "en": "simmer", "zh": "燉，煨" },
{ "en": "retrench", "zh": "減少，節約" },
{ "en": "discredit", "zh": "使失去權威性，破壞名譽" },
{ "en": "curb", "zh": "阻止，控制" },
{ "en": "process", "zh": "加工" },
{ "en": "intercept", "zh": "中途攔截" },
{ "en": "segregate", "zh": "隔離，分開" },
{ "en": "quarantine", "zh": "隔離檢疫" },
{ "en": "seclude", "zh": "隔絕，隱退，隱秘" },
{ "en": "appeal", "zh": "呼籲，懇求，上訴" },
{ "en": "lift", "zh": "解除，提起精神" },
{ "en": "rescind", "zh": "廢止，取消" },
{ "en": "audit", "zh": "查帳" },
{ "en": "condemn", "zh": "非難，判罪" },
{ "en": "condone", "zh": "寬恕，容忍" },
{ "en": "deviate", "zh": "偏離，跑題" },
{ "en": "disabuse", "zh": "解惑，矯正" },
{ "en": "disavow", "zh": "否認" },
{ "en": "transfuse", "zh": "輸血" },
{ "en": "mingle", "zh": "交往，混合" },
{ "en": "forfeit", "zh": "沒收" },
{ "en": "staple", "zh": "用訂書器釘；主要的，重要的（形容詞）" },
{ "en": "deregulate", "zh": "解除對---的管制" },
{ "en": "block", "zh": "阻擋；樓（名詞）" },
{ "en": "launch", "zh": "推出新產品，實施" },
{ "en": "house", "zh": "為---提供住房" },
{ "en": "expel", "zh": "開除，驅除" },
{ "en": "reimburse", "zh": "報銷，退款" },
{ "en": "observe", "zh": "遵守" },
{ "en": "syndicate", "zh": "多家報刊同時發表" },
{ "en": "commute", "zh": "通勤" },
{ "en": "rotate", "zh": "旋轉，迴圈" },
{ "en": "implement", "zh": "實行" },
{ "en": "liquidate", "zh": "清算，清償債務" },
{ "en": "accrue", "zh": "增長，自然增殖" },
{ "en": "fragile", "zh": "易碎的" },
{ "en": "latter", "zh": "後者" },
{ "en": "latest", "zh": "最新的" },
{ "en": "later", "zh": "過後，稍後" },
{ "en": "eligible", "zh": "合格的" },
{ "en": "illegible", "zh": "難懂的" },
{ "en": "edible", "zh": "可食用的" },
{ "en": "audible", "zh": "可聽到的" },
{ "en": "duplicate", "zh": "副本的，複製的" },
{ "en": "potamic", "zh": "河川的" },
{ "en": "faulty", "zh": "有錯誤的" },
{ "en": "supersonic", "zh": "超音速的" },
{ "en": "foremost", "zh": "首要的" },
{ "en": "affluent", "zh": "富足的" },
{ "en": "explicit", "zh": "明晰的" },
{ "en": "implicit", "zh": "暗含的" },
{ "en": "hustle-bustle", "zh": "熙來攘往" },
{ "en": "obese", "zh": "肥胖的" },
{ "en": "manifold", "zh": "各樣的，多種的" },
{ "en": "imprudent", "zh": "輕率的" },
{ "en": "effete", "zh": "疲憊的，枯竭的" },
{ "en": "ebullient", "zh": "沸騰的，熱情洋溢的" },
{ "en": "enervated", "zh": "無力的，衰弱的" },
{ "en": "spacious", "zh": "寬敞的" },
{ "en": "selective", "zh": "精挑細選的" },
{ "en": "precocious", "zh": "早熟的，過早的" },
{ "en": "remiss", "zh": "疏忽的" },
{ "en": "facile", "zh": "容易的，流暢的" },
{ "en": "intangible", "zh": "無形的" },
{ "en": "illicit", "zh": "不合法的" },
{ "en": "diagonal", "zh": "對角線的" },
{ "en": "methodical", "zh": "有條不紊的" },
{ "en": "definitive", "zh": "決定性的，明確的" },
{ "en": "plausible", "zh": "似合理的" },
{ "en": "propitious", "zh": "吉祥的，有利的" },
{ "en": "auspicious", "zh": "吉祥的" },
{ "en": "intelligible", "zh": "可理解的，可識別的" },
{ "en": "inflammable", "zh": "易燃的" },
{ "en": "nonflammable", "zh": "不易燃的" },
{ "en": "quality", "zh": "高品質的" },
{ "en": "state-of-the-art", "zh": "最新水準的" },
{ "en": "illegitimate", "zh": "不合法的，私生的" },
{ "en": "tailored", "zh": "定制的" },
{ "en": "custom-made", "zh": "特製的" },
{ "en": "mandatory", "zh": "強制性的" },
{ "en": "provisional", "zh": "暫時的，臨時的" },
{ "en": "luxurious", "zh": "奢侈的" },
{ "en": "bear market", "zh": "熊市（市場普遍看跌）" },
{ "en": "bull market", "zh": "牛市（市場普遍看漲）" },
{ "en": "hygienic", "zh": "衛生的" },
{ "en": "sanitary", "zh": "乾淨的" },
{ "en": "tricky", "zh": "棘手的，複雜的" },
{ "en": "languishing", "zh": "衰弱的" },
{ "en": "president", "zh": "總裁，董事" },
{ "en": "manager", "zh": "負責人，經理" },
{ "en": "director", "zh": "主管，處長" },
{ "en": "supervisor", "zh": "管理者，監督人" },
{ "en": "leader", "zh": "領導人" },
{ "en": "receptionist", "zh": "接待員" },
{ "en": "representative", "zh": "代表，代理人" },
{ "en": "boss", "zh": "上司" },
{ "en": "porter", "zh": "服務員，搬運工" },
{ "en": "secretary", "zh": "秘書" },
{ "en": "crew", "zh": "全體工作人員" },
{ "en": "clerk", "zh": "職員，辦事員" },
{ "en": "colleague", "zh": "同事" },
{ "en": "consultant", "zh": "顧問" },
{ "en": "advisor", "zh": "顧問" },
{ "en": "counselor", "zh": "顧問" },
{ "en": "captain", "zh": "船長" },
{ "en": "staff", "zh": "員工" },
{ "en": "employee", "zh": "員工" },
{ "en": "worker", "zh": "工人" },
{ "en": "labor", "zh": "勞工" },
{ "en": "member", "zh": "成員" },
{ "en": "employer", "zh": "雇主" },
{ "en": "engineer", "zh": "工程師" },
{ "en": "executive", "zh": "行政官，高層主管" },
{ "en": "attendant", "zh": "服務員，出席者" },
{ "en": "janitor", "zh": "看門人，清潔員" },
{ "en": "predecessor", "zh": "前任，前輩" },
{ "en": "assistant", "zh": "助理" },
{ "en": "conductor", "zh": "領導者，管理人" },
{ "en": "operator", "zh": "操作者" },
{ "en": "patron", "zh": "贊助人" },
{ "en": "advocate", "zh": "提倡者" },
{ "en": "sponsorship", "zh": "資助者" },
{ "en": "investor", "zh": "投資者" },
{ "en": "shareholder", "zh": "股東" },
{ "en": "landlord", "zh": "房東" },
{ "en": "tenant", "zh": "房客" },
{ "en": "customer", "zh": "顧客" },
{ "en": "guest", "zh": "客人" },
{ "en": "client", "zh": "客戶" },
{ "en": "recruit", "zh": "新手，新兵" },
{ "en": "participant", "zh": "參與者" },
{ "en": "expert", "zh": "專家" },
{ "en": "specialist", "zh": "專家" },
{ "en": "plumber", "zh": "水管工" },
{ "en": "carpenter", "zh": "木匠" },
{ "en": "tailor", "zh": "裁縫師" },
{ "en": "painter", "zh": "畫家，油漆工" },
{ "en": "repairperson", "zh": "維修人員" },
{ "en": "surgeon", "zh": "外科醫生" },
{ "en": "photographer", "zh": "攝影師，照相師" },
{ "en": "architect", "zh": "建築師" },
{ "en": "waiter", "zh": "男服務生" },
{ "en": "waitress", "zh": "女服務生" },
{ "en": "musician", "zh": "音樂家" },
{ "en": "technician", "zh": "技術師" },
{ "en": "artist", "zh": "藝術家" },
{ "en": "diplomat", "zh": "外交官" },
{ "en": "demographer", "zh": "人口統計學家" },
{ "en": "pilot", "zh": "領航員" },
{ "en": "tutor", "zh": "家庭教師，私人教師" },
{ "en": "dentist", "zh": "牙醫" },
{ "en": "bellboy", "zh": "旅館大廳服務生" },
{ "en": "scientist", "zh": "科學家" },
{ "en": "flight attendant", "zh": "空中服務人員" },
{ "en": "accountant", "zh": "會計師，會計人員" },
{ "en": "lawyer", "zh": "律師" },
{ "en": "teller", "zh": "銀行出納員" },
{ "en": "housekeeper", "zh": "管家" },
{ "en": "stockbroker", "zh": "股票（或證券）經紀人" },
{ "en": "speaker", "zh": "演講者" },
{ "en": "attendee", "zh": "出席者，在場者" },
{ "en": "audience", "zh": "聽眾，觀眾" },
{ "en": "tourist", "zh": "旅客" },
{ "en": "visitor", "zh": "訪客，來賓" },
{ "en": "passenger", "zh": "乘客" },
{ "en": "pedestrian", "zh": "步行者，行人" },
{ "en": "literate", "zh": "有文化修養的人" },
{ "en": "sibling", "zh": "兄弟姐妹" },
{ "en": "kith and kin", "zh": "親朋好友" },
{ "en": "civilian", "zh": "平民百姓" },
{ "en": "pensioner", "zh": "領養老金者" },
{ "en": "victim", "zh": "受害者，犧牲者，遇難者" },
{ "en": "elite", "zh": "精英，優秀分子" },
{ "en": "vanguard", "zh": "先鋒" },
{ "en": "competitor", "zh": "競爭對手" },
{ "en": "immigrant", "zh": "移入者" },
{ "en": "collector", "zh": "收藏家" },
{ "en": "witness", "zh": "目擊者" },
{ "en": "applicant", "zh": "求職者" },
{ "en": "host", "zh": "男主人" },
{ "en": "hostess", "zh": "女主人" },
{ "en": "heavenly body", "zh": "天體" },
{ "en": "astrology", "zh": "占星術" },
{ "en": "astronomy", "zh": "天文學" },
{ "en": "constellation", "zh": "星座" },
{ "en": "galaxy", "zh": "銀河" },
{ "en": "galactic nebula", "zh": "銀河星雲" },
{ "en": "satellite", "zh": "衛星" },
{ "en": "planet", "zh": "行星" },
{ "en": "asteroid", "zh": "小行星" },
{ "en": "meteor", "zh": "流星" },
{ "en": "meteorite", "zh": "隕石" },
{ "en": "hydrochloric", "zh": "鹽酸的" },
{ "en": "sulfuric acid", "zh": "硫酸" },
{ "en": "reduction", "zh": "還原" },
{ "en": "oxygen", "zh": "氧" },
{ "en": "hydrogen", "zh": "氫" },
{ "en": "nitrogen", "zh": "氮" },
{ "en": "carbon", "zh": "碳" },
{ "en": "neutralize", "zh": "中和" },
{ "en": "filter", "zh": "過濾" },
{ "en": "deposit", "zh": "沉澱" },
{ "en": "oxidize", "zh": "氧化" },
{ "en": "acid", "zh": "酸" },
{ "en": "alkalinity", "zh": "鹼性" },
{ "en": "saturation", "zh": "飽和" },
{ "en": "evaporation", "zh": "蒸發" },
{ "en": "chemical symbol", "zh": "化學記號" },
{ "en": "chemical action", "zh": "化學作用" },
{ "en": "chemical reaction", "zh": "化學反應" },
{ "en": "chemical equation", "zh": "化學方程式" },
{ "en": "lead", "zh": "鉛" },
{ "en": "zinc", "zh": "鋅" },
{ "en": "aluminum", "zh": "鋁" },
{ "en": "cadmium", "zh": "鎘" },
{ "en": "uranium", "zh": "鈾" },
{ "en": "tin", "zh": "錫" },
{ "en": "alloy", "zh": "合金" },
{ "en": "earth's axis", "zh": "地軸" },
{ "en": "latitude", "zh": "緯度" },
{ "en": "longitude", "zh": "經度" },
{ "en": "subtropical", "zh": "亞熱帶的" },
{ "en": "subfrigid", "zh": "亞寒帶的" },
{ "en": "archipelago", "zh": "群島" },
{ "en": "humidity", "zh": "濕度" },
{ "en": "air current", "zh": "氣流" },
{ "en": "front", "zh": "鋒面" },
{ "en": "earthquake", "zh": "地震" },
{ "en": "epicenter", "zh": "震央" },
{ "en": "erosion", "zh": "侵蝕" },
{ "en": "reef", "zh": "礦脈；暗礁" },
{ "en": "glacier", "zh": "冰河" },
{ "en": "iceberg", "zh": "冰山" },
{ "en": "meander", "zh": "曲折（的河流）" },
{ "en": "tributary", "zh": "支流" },
{ "en": "delta", "zh": "三角洲" },
{ "en": "generate", "zh": "發電" },
{ "en": "charge", "zh": "充電" },
{ "en": "ammeter", "zh": "電流錶" },
{ "en": "voltmeter", "zh": "電壓表" },
{ "en": "electrode", "zh": "電極" },
{ "en": "cathode", "zh": "陰極" },
{ "en": "anode", "zh": "陽極" },
{ "en": "electronics", "zh": "電子工學" },
{ "en": "semi-conductor", "zh": "半導體" },
{ "en": "terminal", "zh": "接頭" },
{ "en": "appointment", "zh": "約會，約定" },
{ "en": "attendance", "zh": "出席人數；出席" },
{ "en": "cabinet", "zh": "櫥櫃" },
{ "en": "calendar", "zh": "日曆；月曆；行事曆" },
{ "en": "clerk", "zh": "辦事員，書記" },
{ "en": "directory", "zh": "人名住址簿" },
{ "en": "duplicate", "zh": "複製；副本" },
{ "en": "filing", "zh": "歸檔" },
{ "en": "in-tray", "zh": "待處理文件盒" },
{ "en": "monitor", "zh": "監視；追蹤；檢測" },
{ "en": "out-tray", "zh": "已處理文件盒" },
{ "en": "partition", "zh": "分隔；分隔物（如牆壁等）" },
{ "en": "postage", "zh": "郵費" },
{ "en": "punctuality", "zh": "準時；守時" },
{ "en": "schedule", "zh": "時間表；計畫表" },
{ "en": "shift", "zh": "換班；輪班；值班" },
{ "en": "staff", "zh": "全體職員" },
{ "en": "strike", "zh": "罷工" },
{ "en": "task", "zh": "工作，任務" },
{ "en": "work force", "zh": "工作人員；勞動人口" },
{ "en": "assignment", "zh": "分配；工作，分派" },
{ "en": "bulletin", "zh": "公報；告示；定期報告書" },
{ "en": "calculator", "zh": "計算器" },
{ "en": "carbon copy", "zh": "用複寫紙複製的副本" },
{ "en": "colleague", "zh": "同事，同僚" },
{ "en": "document", "zh": "文件，證件" },
{ "en": "extension", "zh": "分機（電話）；延期" },
{ "en": "intercom", "zh": "對講機" },
{ "en": "memo", "zh": "便條；便箋；備忘錄" },
{ "en": "operator", "zh": "接線生" },
{ "en": "overtime", "zh": "加班的時間" },
{ "en": "portfolio", "zh": "作品夾，公事包" },
{ "en": "printed matter", "zh": "印刷品" },
{ "en": "receptionist", "zh": "接待員" },
{ "en": "secretary", "zh": "秘書" },
{ "en": "shorthand", "zh": "速記，速記法" },
{ "en": "stapler", "zh": "釘書機" },
{ "en": "tardy", "zh": "遲緩；遲到的；遲延的" },
{ "en": "typist", "zh": "打字員" },
{ "en": "xerox", "zh": "影印" },
{ "en": "allocate", "zh": "撥出；分配；配置" },
{ "en": "applicant", "zh": "申請人" },
{ "en": "authorize", "zh": "授權；委託" },
{ "en": "bonus", "zh": "紅利；額外津貼；獎金" },
{ "en": "capability", "zh": "能力；才幹；潛力；性能" },
{ "en": "collaboration", "zh": "合作；通敵" },
{ "en": "consultation", "zh": "諮詢；商量；會議" },
{ "en": "curriculum vitae", "zh": "履歷" },
{ "en": "eligible", "zh": "合格的，合適的" },
{ "en": "employer", "zh": "雇主" },
{ "en": "executive", "zh": "行政或管理人員" },
{ "en": "income", "zh": "收入或所得" },
{ "en": "lay off", "zh": "（暫時）解雇" },
{ "en": "occupation", "zh": "職業" },
{ "en": "part-time", "zh": "兼任的；兼職的" },
{ "en": "permanent", "zh": "不變的，永久的" },
{ "en": "promote", "zh": "升遷；促銷" },
{ "en": "recruit", "zh": "吸收；徵募" },
{ "en": "resume", "zh": "履歷表" },
{ "en": "salary", "zh": "薪水" },
{ "en": "amateur", "zh": "業餘技術家；外行人；非專家" },
{ "en": "appoint", "zh": "任命；指定" },
{ "en": "benefit", "zh": "有益於；受益" },
{ "en": "candidate", "zh": "候選人" },
{ "en": "certificate", "zh": "憑證；證書" },
{ "en": "competent", "zh": "有能力的，勝任的" },
{ "en": "coordinate", "zh": "協調；調整" },
{ "en": "deadline", "zh": "截至期限" },
{ "en": "employee", "zh": "受雇者" },
{ "en": "evaluation", "zh": "評價；估價" },
{ "en": "expertise", "zh": "專門技術或知識" },
{ "en": "interview", "zh": "會面；面談" },
{ "en": "novice", "zh": "生手；新手；初學者" },
{ "en": "overtime", "zh": "超時" },
{ "en": "pension", "zh": "養老金；退休金" },
{ "en": "personnel", "zh": "全體人員；人事部門" },
{ "en": "recommendation", "zh": "推薦；推薦書；勸告" },
{ "en": "resign", "zh": "辭職" },
{ "en": "retire", "zh": "退休" },
{ "en": "substitute", "zh": "代理人；代用品" },
{ "en": "accrue", "zh": "產生；增加" },
{ "en": "acquisition", "zh": "獲得；習得" },
{ "en": "amplify", "zh": "放大；加強；擴展" },
{ "en": "asset", "zh": "有用的東西；優點；長處" },
{ "en": "buyout", "zh": "買進全部產權或股權；收購全部" },
{ "en": "corporation", "zh": "法人；公司" },
{ "en": "cutback", "zh": "減少；取消" },
{ "en": "enterprise", "zh": "企業" },
{ "en": "equity", "zh": "公平；公正；剩餘財產價值" },
{ "en": "financier", "zh": "財政家；金融業者；資本家；投資者" },
{ "en": "franchise", "zh": "經銷權；加盟權" },
{ "en": "launch", "zh": "開辦；展開；發起；開始" },
{ "en": "monopoly", "zh": "壟斷；獨佔；專賣" },
{ "en": "phase", "zh": "階段" },
{ "en": "profile", "zh": "側面象；略轉；引人矚目的狀態" },
{ "en": "proposition", "zh": "提案；建議；計畫" },
{ "en": "prospectus", "zh": "計畫書；說明書；募股書" },
{ "en": "rival", "zh": "競爭者；對手；匹敵者；勢均力敵者" },
{ "en": "subsidiary", "zh": "子公司" },
{ "en": "track record", "zh": "過去的記錄" },
{ "en": "acquire", "zh": "獲得" },
{ "en": "affiliate", "zh": "支部；分會；子公司" },
{ "en": "assess", "zh": "評估；評定" },
{ "en": "benchmark", "zh": "基準；水準點；標準" },
{ "en": "carry out", "zh": "執行；貫徹；完成" },
{ "en": "cut down", "zh": "削減；縮短" },
{ "en": "embezzle", "zh": "盜用；挪用；侵佔" },
{ "en": "entrepreneur", "zh": "企業家；主辦人" },
{ "en": "expand", "zh": "擴張；擴大" },
{ "en": "firm", "zh": "公司；商行" },
{ "en": "integrate", "zh": "統合；整合" },
{ "en": "merger", "zh": "合併；併吞" },
{ "en": "pending", "zh": "未決定的；待決定的；即將發生" },
{ "en": "preliminary", "zh": "初步的，開始的" },
{ "en": "propose", "zh": "提議；建議" },
{ "en": "prospect", "zh": "期望或預見的事；展望；期望" },
{ "en": "prosperity", "zh": "繁榮；成功；興隆" },
{ "en": "scheme", "zh": "計畫；設計；圖謀" },
{ "en": "thrive", "zh": "茂盛；興旺；繁榮" },
{ "en": "undervalue", "zh": "低估價值；看輕" },
{ "en": "account", "zh": "帳目；帳單；帳戶" },
{ "en": "balance", "zh": "餘額；差額" },
{ "en": "bond", "zh": "債券" },
{ "en": "chamber of commerce", "zh": "商會" },
{ "en": "credit", "zh": "信任；信用；信譽；功勞；榮譽；存款數額；融資；賒銷" },
{ "en": "debt", "zh": "債；債務" },
{ "en": "deficit", "zh": "赤字；虧損額" },
{ "en": "depreciation", "zh": "跌價；貶值" },
{ "en": "devaluation", "zh": "貶值" },
{ "en": "endorse", "zh": "贊同；支持；簽名；背書" },
{ "en": "exempt", "zh": "被免除的；豁免的" },
{ "en": "expense", "zh": "消耗；消費" },
{ "en": "fluctuation", "zh": "波動；起伏；漲落" },
{ "en": "gross", "zh": "總共的；全部的" },
{ "en": "inflation", "zh": "物價飛漲；通貨膨脹" },
{ "en": "overdraft", "zh": "透支；透支額" },
{ "en": "profit", "zh": "利潤；收益；營利" },
{ "en": "revenue", "zh": "收益；歲入；稅收" },
{ "en": "stock", "zh": "公債；證券；股票" },
{ "en": "withdraw", "zh": "收回；取回；撤回；提款" },
{ "en": "accountant", "zh": "會計師；會計員" },
{ "en": "bankrupt", "zh": "破產的；倒閉的" },
{ "en": "capital", "zh": "資金；資本" },
{ "en": "convert", "zh": "轉換；改變" },
{ "en": "currency", "zh": "貨幣；流通；通用" },
{ "en": "deduction", "zh": "扣除；扣除額" },
{ "en": "deposit", "zh": "付押金；付保證金" },
{ "en": "depression", "zh": "不景氣；憂傷；消沉；沮喪" },
{ "en": "discrepancy", "zh": "差異；不同；不一致" },
{ "en": "estimate", "zh": "估計；估價" },
{ "en": "expenditure", "zh": "消費；開銷" },
{ "en": "fiscal", "zh": "財政的；會計的" },
{ "en": "fund", "zh": "基金；專款" },
{ "en": "holding", "zh": "土地；財產" },
{ "en": "ledger", "zh": "總帳；分類帳" },
{ "en": "overdue", "zh": "過期未付的" },
{ "en": "remuneration", "zh": "報酬；酬勞" },
{ "en": "shareholder", "zh": "股東" },
{ "en": "stockbroker", "zh": "證券和股票經紀人" },
{ "en": "yield", "zh": "生產量；收益；生產；產生" },
{ "en": "bid", "zh": "出價；投標；喊價" },
{ "en": "commercial", "zh": "商業化；商用的；營利的" },
{ "en": "competitor", "zh": "競爭者；對手" },
{ "en": "consolidate", "zh": "結合；合併；強化；鞏固" },
{ "en": "contract", "zh": "契約；合同" },
{ "en": "corporate", "zh": "全體的；團體的；公司的；法人的" },
{ "en": "credible", "zh": "可信的；可靠的" },
{ "en": "debit", "zh": "借方；借項" },
{ "en": "earnings", "zh": "薪水；工資；收益" },
{ "en": "export", "zh": "輸出；出口" },
{ "en": "haggle", "zh": "討價還價" },
{ "en": "import", "zh": "輸入；進口" },
{ "en": "invoice", "zh": "發票；發貨清單；完成工作的清單（明列數量和價錢）" },
{ "en": "long-range", "zh": "長期的；遠程的" },
{ "en": "stock", "zh": "現貨；存貨" },
{ "en": "payment", "zh": "支付；付款" },
{ "en": "quote", "zh": "報價" },
{ "en": "supply", "zh": "供應品；供應物；庫存" },
{ "en": "tariff", "zh": "關稅" },
{ "en": "voucher", "zh": "保證人；憑證；憑單；折價券" },
{ "en": "bill of lading", "zh": "提貨單" },
{ "en": "commodity", "zh": "商品；農產品" },
{ "en": "consignee", "zh": "收件人；受託人" },
{ "en": "consumer", "zh": "消費者；顧客" },
{ "en": "contractor", "zh": "立契約人；承包商" },
{ "en": "cost-effective", "zh": "符合成本效益的" },
{ "en": "dealer", "zh": "商人；業者" },
{ "en": "due", "zh": "應付的；到期的；該發生的" },
{ "en": "endorse", "zh": "背書；支持；贊同" },
{ "en": "forward", "zh": "送到，轉號" },
{ "en": "headquarters", "zh": "總公司；總部；司令部" },
{ "en": "inventory", "zh": "詳細目錄；清單；存貨" },
{ "en": "letter of credit", "zh": "信用狀" },
{ "en": "order", "zh": "匯單;訂貨；訂單；匯票" },
{ "en": "patent", "zh": "專利；取得…的專利" },
{ "en": "quota", "zh": "定量；定額；配額" },
{ "en": "shipment", "zh": "一批貨" },
{ "en": "surplus", "zh": "過剩的量；盈餘,過剩的；剩餘的" },
{ "en": "trademark", "zh": "注冊商標" },
{ "en": "warehouse", "zh": "倉庫；貨價；大商店" },
{ "en": "adjourn", "zh": "暫時；休會；延期" },
{ "en": "agreement", "zh": "同意；協定" },
{ "en": "amendment", "zh": "修正" },
{ "en": "approval", "zh": "贊成；同意" },
{ "en": "attentive", "zh": "注意的；留心的專心的" },
{ "en": "board", "zh": "理事會；委員會；董事會" },
{ "en": "brainstorm", "zh": "腦力激蕩，集思廣益" },
{ "en": "concede", "zh": "容忍；容許；讓步" },
{ "en": "conference", "zh": "會議；協商；討論會" },
{ "en": "convention", "zh": "慣例；常規；習俗；會議；" },
{ "en": "convince", "zh": "使信服" },
{ "en": "cross-reference", "zh": "前後參照；（使）前後參照" },
{ "en": "delegate", "zh": "代表" },
{ "en": "demand", "zh": "要求；強求" },
{ "en": "dispute", "zh": "爭端；爭執；糾紛；" },
{ "en": "negotiation", "zh": "協商；談判" },
{ "en": "persuade", "zh": "說服；勸服" },
{ "en": "postpone", "zh": "延遲；延期" },
{ "en": "reconcile", "zh": "調和；調解" },
{ "en": "settlement", "zh": "協議；支付" },
{ "en": "agenda", "zh": "議程" },
{ "en": "alternative", "zh": "可供選擇的事物、方式等" },
{ "en": "announce", "zh": "通告；宣佈；宣告；公諸於眾" },
{ "en": "articulate", "zh": "能清楚有力表達思想感情的；表達能力強的" },
{ "en": "attorney", "zh": "律師" },
{ "en": "breakthrough", "zh": "突破；重大進展" },
{ "en": "compromise", "zh": "妥協；折衷；和解" },
{ "en": "conclusive", "zh": "決定性的；勿庸置疑的" },
{ "en": "consensus", "zh": "一致的意見；共識" },
{ "en": "converse", "zh": "談話；交談" },
{ "en": "criterion", "zh": "規範；標準" },
{ "en": "decline", "zh": "衰落；衰退；下降" },
{ "en": "demonstration", "zh": "示範；實證；（遊行）示威" },
{ "en": "diplomacy", "zh": "外交手腕；交際手段" },
{ "en": "dissuade", "zh": "勸阻" },
{ "en": "on behalf of", "zh": "代表" },
{ "en": "petition", "zh": "請願（書）；請願" },
{ "en": "premise", "zh": "前提" },
{ "en": "seminar", "zh": "研討會；討論課；講習會" },
{ "en": "statement", "zh": "聲明；陳述" },
{ "en": "advance", "zh": "前進；進展" },
{ "en": "capacity", "zh": "容量；才能；能力" },
{ "en": "component", "zh": "構成要素；成分；零件" },
{ "en": "device", "zh": "裝置；設備；圖案；設計" },
{ "en": "engineer", "zh": "工程師" },
{ "en": "facilitate", "zh": "促進；使（更）容易" },
{ "en": "fuel", "zh": "燃料" },
{ "en": "generator", "zh": "發電機；產生器" },
{ "en": "innovative", "zh": "創新；革新的" },
{ "en": "inventor", "zh": "發明家" },
{ "en": "leading edge", "zh": "居領先優勢的" },
{ "en": "malfunction", "zh": "故障；發生故障，機能失常" },
{ "en": "mode", "zh": "樣式；模式；方式；風尚；時尚" },
{ "en": "operate", "zh": "操作；運轉；經營" },
{ "en": "outlet", "zh": "出口；排水口；銷售店；商行；插座；銷路" },
{ "en": "portable", "zh": "可攜帶的；輕便的" },
{ "en": "raw material", "zh": "原料" },
{ "en": "satellite", "zh": "衛星" },
{ "en": "specification", "zh": "說明；詳述" },
{ "en": "substandard", "zh": "標準以下的" },
{ "en": "automaton", "zh": "自動操作裝置；機器人" },
{ "en": "cell(ular)phone", "zh": "移動電話；手機" },
{ "en": "consecutive", "zh": "連續的；連貫的" },
{ "en": "devise", "zh": "設計；發明；策劃" },
{ "en": "equipment", "zh": "裝備；設備" },
{ "en": "facility", "zh": "便利的設施；設備" },
{ "en": "gadget", "zh": "小巧的機械裝置；小玩意" },
{ "en": "hands-on", "zh": "實地操作的；親身體驗的" },
{ "en": "inspect", "zh": "檢查；審查；視察" },
{ "en": "laboratory", "zh": "實驗室" },
{ "en": "maintenance", "zh": "維護；保養" },
{ "en": "manual", "zh": "使用手冊，指南；手工的" },
{ "en": "network", "zh": "網路系統；廣播、電視網；電腦網" },
{ "en": "outage", "zh": "電力中斷；斷電" },
{ "en": "petroleum", "zh": "石油" },
{ "en": "procedure", "zh": "程式；手續" },
{ "en": "reverse", "zh": "相反的；顛倒的" },
{ "en": "solar", "zh": "(源自)太陽的；依太陽而運行的" },
{ "en": "static", "zh": "靜電干擾；靜止的；靜態的；靜電的" },
{ "en": "turn down", "zh": "關小（聲）" },
{ "en": "access", "zh": "進入；接近；使用；取得" },
{ "en": "automatically", "zh": "無意識的；不自覺的；自動的" },
{ "en": "cable", "zh": "纜線；電纜" },
{ "en": "compliance", "zh": "順從；服從；附和；屈從" },
{ "en": "cutting edge", "zh": "尖刻；尖銳；先鋒地位 尖端的" },
{ "en": "delete", "zh": "刪除" },
{ "en": "digital", "zh": "數位的；數位顯示的" },
{ "en": "download", "zh": "下載" },
{ "en": "hacker", "zh": "熱衷電腦的人，駭客" },
{ "en": "input", "zh": "輸入電腦" },
{ "en": "Internet", "zh": "國際互聯網" },
{ "en": "laptop", "zh": "筆記本電腦" },
{ "en": "multimedia", "zh": "多媒體" },
{ "en": "retrieval", "zh": "取回；恢復" },
{ "en": "search engine", "zh": "搜索引擎" },
{ "en": "shut down", "zh": "使關閉；使停業" },
{ "en": "state-of-the-art", "zh": "使用最先進技術的；達到最高水準的" },
{ "en": "terminology", "zh": "專業術語；專有名詞" },
{ "en": "troubleshooting", "zh": "檢修；解決困難的" },
{ "en": "up-to-date", "zh": "最近的；最新的" },
{ "en": "activate", "zh": "使活動；觸發；啟動" },
{ "en": "browse", "zh": "流覽；隨便翻閱" },
{ "en": "command", "zh": "指令；命令；掌握" },
{ "en": "configuration", "zh": "結構；構造；配置" },
{ "en": "database", "zh": "資料庫" },
{ "en": "desktop", "zh": "桌上型的" },
{ "en": "downgrade", "zh": "降級；使降職" },
{ "en": "floppy(disk)", "zh": "軟碟" },
{ "en": "hyperlink", "zh": "超鏈結" },
{ "en": "install", "zh": "安裝；安置" },
{ "en": "know-how", "zh": "技能；專業知識；竅門" },
{ "en": "modern", "zh": "數據機" },
{ "en": "omit", "zh": "忽略；刪除；疏忽" },
{ "en": "scanner", "zh": "掃描器" },
{ "en": "server", "zh": "伺服器" },
{ "en": "spreadsheet", "zh": "電子製表軟體；試算表" },
{ "en": "switch", "zh": "開關；驟變" },
{ "en": "transmission", "zh": "傳輸；傳送" },
{ "en": "upgrade", "zh": "升級；提升" },
{ "en": "virus", "zh": "濾過性病毒；電腦病毒" },
{ "en": "advertisement", "zh": "廣告" },
{ "en": "appendix", "zh": "附錄" },
{ "en": "attach", "zh": "貼上；附上；附加" },
{ "en": "campaign", "zh": "戰役；競選活動；宣傳活動" },
{ "en": "cohesive", "zh": "有粘著力的；有結合力的；凝聚性的" },
{ "en": "confidential", "zh": "秘密的；機密的" },
{ "en": "correspondence", "zh": "通信；信件" },
{ "en": "dictate", "zh": "口述；支配；命令" },
{ "en": "elaborate", "zh": "詳盡說明；詳盡的；精心製作的" },
{ "en": "forward", "zh": "轉寄；發送" },
{ "en": "inquire", "zh": "調查；詢問" },
{ "en": "jot down", "zh": "略記下；匆匆記下" },
{ "en": "leaflet", "zh": "傳單" },
{ "en": "notify", "zh": "通知；告知" },
{ "en": "promote", "zh": "發揚；晉升；促進" },
{ "en": "publicity", "zh": "公開；宣傳；盡人皆知" },
{ "en": "response", "zh": "回應" },
{ "en": "revise", "zh": "修訂；修改；校訂" },
{ "en": "slogan", "zh": "口號；標語" },
{ "en": "urgent", "zh": "緊急的；急迫的" },
{ "en": "affirm", "zh": "堅稱；聲明；斷言；確認" },
{ "en": "ASAP", "zh": "as soon as possible 越快越好" },
{ "en": "banner", "zh": "標語；旗幟" },
{ "en": "circular", "zh": "廣告；傳單；通告" },
{ "en": "composition", "zh": "寫作；作品；作文；作曲" },
{ "en": "convene", "zh": "集合；聚集；開會" },
{ "en": "courier", "zh": "遞送急件的信差；郵物專遞公司" },
{ "en": "draft", "zh": "草稿；匯票" },
{ "en": "enclose", "zh": "裝入；放入封套" },
{ "en": "inform", "zh": "通知；告知" },
{ "en": "issue", "zh": "流出；放出；發行；發佈" },
{ "en": "layout", "zh": "規劃；設計；編排" },
{ "en": "legible", "zh": "（字跡）可以辨認的；易讀的" },
{ "en": "postage", "zh": "郵資" },
{ "en": "proofread", "zh": "校正；校對" },
{ "en": "regarding", "zh": "關於；有關" },
{ "en": "restate", "zh": "再聲明；重新敍述；（換一種方式）重說" },
{ "en": "signature", "zh": "簽字；簽名" },
{ "en": "stationery", "zh": "文具；信紙；信箋" },
{ "en": "write-up", "zh": "報告書 write up 詳細寫" },
{ "en": "accommodation", "zh": "適應；住所；膳宿" },
{ "en": "boarding pass", "zh": "登機牌" },
{ "en": "brochure", "zh": "小冊子" },
{ "en": "checkout", "zh": "結帳退房的時間 check out 辦理退房；結帳離開" },
{ "en": "confirmation", "zh": "確認" },
{ "en": "customs", "zh": "海關；關稅" },
{ "en": "departure", "zh": "離開；出發" },
{ "en": "en route", "zh": "在途中" },
{ "en": "expedition", "zh": "探險；遠征隊" },
{ "en": "flight", "zh": "飛行；航班；航程" },
{ "en": "itinerary", "zh": "行程表；旅程" },
{ "en": "lodge", "zh": "小屋；旅館" },
{ "en": "luxurious", "zh": "奢華的；非常舒適的" },
{ "en": "motel", "zh": "汽車旅館" },
{ "en": "packing", "zh": "包裝；打包" },
{ "en": "peak season", "zh": "旺季" },
{ "en": "reservation", "zh": "預約；預訂；保留" },
{ "en": "sightseeing", "zh": "觀光；遊覽" },
{ "en": "suite", "zh": "（旅館的）套房" },
{ "en": "valid", "zh": "依法有效的；有效的" },
{ "en": "baggage claim", "zh": "行李提領處" },
{ "en": "breathtaking", "zh": "驚人的；驚豔的；驚險的" },
{ "en": "carry-on", "zh": "登機行李；手提行李" },
{ "en": "concierge", "zh": "管理員；門房" },
{ "en": "cruise", "zh": "乘船遊覽" },
{ "en": "deluxe", "zh": "豪華的；高級的" },
{ "en": "destination", "zh": "目的地" },
{ "en": "exotic", "zh": "異國風情的；異國的" },
{ "en": "fasten", "zh": "系緊；拴住；扣住" },
{ "en": "flight attendant", "zh": "空中服務員" },
{ "en": "jet lag", "zh": "時差" },
{ "en": "luggage", "zh": "行李" },
{ "en": "metal detector", "zh": "金屬探測器" },
{ "en": "overseas", "zh": "在海外的，國外的（注意一般使用時都有 s）" },
{ "en": "passenger", "zh": "乘客；旅客" },
{ "en": "porter", "zh": "腳夫；門房" },
{ "en": "round-trip", "zh": "來回的，雙程的" },
{ "en": "stopover", "zh": "中途停留" },
{ "en": "vacant", "zh": "空的，未被佔用的" },
{ "en": "voyage", "zh": "旅行；航行" },
{ "en": "accelerate", "zh": "加速；促進；前進" },
{ "en": "aircraft", "zh": "飛機；飛行器；航空器" },
{ "en": "arrival", "zh": "到達；抵達" },
{ "en": "buckle up", "zh": "系安全帶" },
{ "en": "cargo", "zh": "貨物" },
{ "en": "convertible", "zh": "敞篷車" },
{ "en": "crash landing", "zh": "迫降" },
{ "en": "delay", "zh": "耽擱；延遲" },
{ "en": "forbid", "zh": "禁止" },
{ "en": "ground crew", "zh": "地勤人員" },
{ "en": "jaywalk", "zh": "不遵守交通規則穿越馬路；闖紅燈" },
{ "en": "launch", "zh": "發射；開始" },
{ "en": "navigate", "zh": "航行；駕駛" },
{ "en": "pilot", "zh": "飛行員" },
{ "en": "route", "zh": "路徑；路線" },
{ "en": "seat belt", "zh": "安全帶" },
{ "en": "subway", "zh": "地鐵 （注意區分 highway ,freeway ,metro)" },
{ "en": "taxicab", "zh": "計程車" },
{ "en": "transit", "zh": "運輸；通過" },
{ "en": "vehicle", "zh": "交通工具；車輛" },
{ "en": "acrophobia", "zh": "恐高症" },
{ "en": "airliner", "zh": "大型客機" },
{ "en": "aviation", "zh": "飛行；航空學" },
{ "en": "cabin", "zh": "小屋；客艙；機艙" },
{ "en": "commuter", "zh": "通勤者" },
{ "en": "conveyance", "zh": "運輸；交通工具" },
{ "en": "crossroads", "zh": "十字路口" },
{ "en": "ferry", "zh": "渡輪" },
{ "en": "freight", "zh": "貨運；貨物" },
{ "en": "intersection", "zh": "" },
{ "en": "jeopardy", "zh": "風險；危險；危難" },
{ "en": "life vest", "zh": "救生衣" },
{ "en": "pedestrian", "zh": "行人；步行者" },
{ "en": "restriction", "zh": "限制；約束" },
{ "en": "runway", "zh": "飛機跑道" },
{ "en": "shortcut", "zh": "近路；捷徑" },
{ "en": "take off", "zh": "起飛" },
{ "en": "timetable", "zh": "時間表；時刻表" },
{ "en": "transport", "zh": "運輸；交通工具；運輸系" },
{ "en": "via", "zh": "經由；借由" },
{ "en": "affordable", "zh": "負擔的起的" },
{ "en": "bazaar", "zh": "市場；集市" },
{ "en": "client", "zh": "顧客；委託人" },
{ "en": "customer", "zh": "顧客；客戶" },
{ "en": "discount", "zh": "折扣" },
{ "en": "distributor", "zh": "供應商；經銷商" },
{ "en": "expiration", "zh": "終結；期滿" },
{ "en": "itemize", "zh": "詳細列舉；分條列舉" },
{ "en": "latest", "zh": "最新的" },
{ "en": "neon sign", "zh": "霓虹燈招牌" },
{ "en": "pickpocket", "zh": "扒手" },
{ "en": "pushcart", "zh": "手推車" },
{ "en": "receipt", "zh": "收據" },
{ "en": "reimburse", "zh": "償還；補償" },
{ "en": "request", "zh": "請求；要求" },
{ "en": "sample", "zh": "樣品；樣本" },
{ "en": "solicit", "zh": "請求；懇求；祈求" },
{ "en": "trendy", "zh": "時髦的；流行的" },
{ "en": "VIP", "zh": "very important person 貴賓" },
{ "en": "wholesale", "zh": "批發的；批發地" },
{ "en": "bargain", "zh": "便宜貨；廉價品" },
{ "en": "cash register", "zh": "手銀機" },
{ "en": "coupon", "zh": "折價券；贈獎券" },
{ "en": "defective", "zh": "有毛病的；有問題的，有瑕疵的" },
{ "en": "display", "zh": "陳列；展示品" },
{ "en": "drugstore", "zh": "兼賣雜貨的藥房" },
{ "en": "flea market", "zh": "跳蚤市場" },
{ "en": "label", "zh": "標籤；標記" },
{ "en": "modify", "zh": "修改；變更" },
{ "en": "patron", "zh": "顧客；贊助人" },
{ "en": "purchase", "zh": "購買；購得之物" },
{ "en": "quantity", "zh": "量；數量" },
{ "en": "refund", "zh": "退款；退還；賠償" },
{ "en": "replacement", "zh": "代替；替換" },
{ "en": "retailer", "zh": "零售商" },
{ "en": "shopping mall", "zh": "大型購物中心" },
{ "en": "thrift", "zh": "節儉；節約" },
{ "en": "vender", "zh": "小販" },
{ "en": "warranty", "zh": "保證；保證書" },
{ "en": "workmanship", "zh": "技巧；手藝" },
{ "en": "alcohol", "zh": "酒精" },
{ "en": "appetite", "zh": "胃口，食欲" },
{ "en": "artificial", "zh": "人造的；仿真的" },
{ "en": "bland", "zh": "淡而無味的；溫和的；無刺激性的" },
{ "en": "chef", "zh": "主廚；大廚" },
{ "en": "crave", "zh": "渴望" },
{ "en": "delicacy", "zh": "佳餚" },
{ "en": "digest", "zh": "消化" },
{ "en": "fragrant", "zh": "有香味的；芳香的" },
{ "en": "ingredient", "zh": "成分；配料；配方" },
{ "en": "liquor", "zh": "烈酒（如威士卡）" },
{ "en": "munch", "zh": "用力嚼；大聲咀嚼" },
{ "en": "palatable", "zh": "美味的；順耳的；怡人的" },
{ "en": "pass up", "zh": "放過；錯過" },
{ "en": "portion", "zh": "部分；一份" },
{ "en": "ravenous", "zh": "飢餓的；貪婪的" },
{ "en": "refreshment", "zh": "茶點" },
{ "en": "silverware", "zh": "銀器；鍍銀餐具" },
{ "en": "specialty", "zh": "專攻；專業；專長；特製品" },
{ "en": "starve", "zh": "餓死；挨餓" },
{ "en": "aperitif", "zh": "飯前酒" },
{ "en": "appetizer", "zh": "開胃菜" },
{ "en": "beverage", "zh": "飲料" },
{ "en": "buffet", "zh": "自助餐" },
{ "en": "chopsticks", "zh": "筷子" },
{ "en": "cuisine", "zh": "烹調" },
{ "en": "dessert", "zh": "餐後甜點" },
{ "en": "entree", "zh": "主菜" },
{ "en": "hors d'oeuvre", "zh": "開胃小菜" },
{ "en": "leftovers", "zh": "剩飯剩菜" },
{ "en": "menu", "zh": "菜單" },
{ "en": "napkin", "zh": "餐巾" },
{ "en": "parched", "zh": "焦幹的；極渴的" },
{ "en": "pastry", "zh": "用麵團和油酥烤成的小甜點心" },
{ "en": "preservative", "zh": "防腐劑" },
{ "en": "recipe", "zh": "食譜；烹飪法；秘訣" },
{ "en": "seasoning", "zh": "調味品；佐料" },
{ "en": "snack", "zh": "小吃；點心 吃點心" },
{ "en": "spice", "zh": "香料；調味品" },
{ "en": "vegetarian", "zh": "素食者"},
{ "en": "acceptance", "zh": "接受；贊同" },
{ "en": "acquaintance", "zh": "相識但是不是很熟的人" },
{ "en": "anniversary", "zh": "周年紀念日" },
{ "en": "associate", "zh": "(1)同事；夥伴 (2)聯想；交往" },
{ "en": "banquet", "zh": "酒席；正式的宴會" },
{ "en": "commitment", "zh": "承諾；許諾" },
{ "en": "courtesy", "zh": "禮貌；禮儀；好意；殷勤" },
{ "en": "distinguished", "zh": "卓越的；傑出的；著名的" },
{ "en": "embrace", "zh": "擁抱；圍繞；包括" },
{ "en": "etiquette", "zh": "禮節；規範" },
{ "en": "farewell", "zh": "一路平安；再見；告別" },
{ "en": "get-together", "zh": "（非正式的社交）聚會" },
{ "en": "greeting", "zh": "致敬；問候；（複數）致意；贊詞" },
{ "en": "hug", "zh": "擁抱；緊抱" },
{ "en": "lavish", "zh": "過分大方的；浪費的；豐富的" },
{ "en": "nosy", "zh": "好管閒事的；愛打聽的" },
{ "en": "offensive", "zh": "令人不快的；討厭的；冒犯的" },
{ "en": "protocol", "zh": "外交禮儀；草約" },
{ "en": "regards", "zh": "問候；致意" },
{ "en": "salute", "zh": "向……打招呼；向……行軍禮；向……表示敬意" },
{ "en": "acknowledge", "zh": "承認；承認……之存在、權力；表示感謝" },
{ "en": "aggressive", "zh": "挑釁的；有侵略性的；有進取心的；積極的" },
{ "en": "apologize", "zh": "道歉" },
{ "en": "attractive", "zh": "引人入勝；有吸引力的；迷人的" },
{ "en": "barrier", "zh": "障礙；障礙物；隔閡" },
{ "en": "compliment", "zh": "讚揚；恭維" },
{ "en": "criticize", "zh": "批評；評論" },
{ "en": "eloquent", "zh": "口才好的；雄辯的" },
{ "en": "encounter", "zh": "相遇；遭遇；偶然碰見；面臨" },
{ "en": "extend", "zh": "延伸；延續；擴大；延長；給予；提供" },
{ "en": "favorable", "zh": "令人滿意的；博得贊許的；有説明的；有利的" },
{ "en": "gossip", "zh": "閒話；流言；說閒話" },
{ "en": "hilarious", "zh": "狂歡的；令人捧腹的" },
{ "en": "intrude", "zh": "闖入；侵入；把……強加諸於" },
{ "en": "modest", "zh": "謙遜的；適度的；樸實的；端莊的" },
{ "en": "nuisance", "zh": "討厭之人、事、物" },
{ "en": "prompt", "zh": "準時的；按時的；迅速的；立刻行動的" },
{ "en": "quarrel", "zh": "爭吵；爭論；吵架" },
{ "en": "run into", "zh": "偶遇；碰上" },
{ "en": "scandal", "zh": "醜聞；引人憤慨之事" },
{ "en": "amuse", "zh": "使歡樂；使愉快；使發笑" },
{ "en": "audience", "zh": "聽眾；觀眾" },
{ "en": "ballet", "zh": "芭蕾舞" },
{ "en": "cable TV", "zh": "有線電視" },
{ "en": "celebrity", "zh": "名人；名聲" },
{ "en": "cinema", "zh": "電影；影片；電影院；電影藝術；電影業" },
{ "en": "composer", "zh": "作曲家" },
{ "en": "conductor", "zh": "指揮家" },
{ "en": "cue", "zh": "暗示；提示" },
{ "en": "drama", "zh": "戲劇；劇本" },
{ "en": "fare", "zh": "車費；票價" },
{ "en": "headline", "zh": "（報紙的）標題" },
{ "en": "newscast", "zh": "新聞廣播" },
{ "en": "periodical", "zh": "雜誌；期刊" },
{ "en": "premiere", "zh": "首次公演；首映" },
{ "en": "rate", "zh": "分級；分等" },
{ "en": "scenario", "zh": "戲劇的情節" },
{ "en": "scriptwriter", "zh": "劇作家；編劇" },
{ "en": "symphony", "zh": "交響曲" },
{ "en": "ticket office", "zh": "售票處" },
{ "en": "applaud", "zh": "鼓掌" },
{ "en": "audition", "zh": "試聽；試演" },
{ "en": "broadcast", "zh": "廣播；宣傳" },
{ "en": "carnival", "zh": "狂歡；歡宴；嘉年華會；巡迴娛樂表演" },
{ "en": "choreography", "zh": "舞蹈設計；編舞" },
{ "en": "circus", "zh": "馬戲團" },
{ "en": "concert", "zh": "音樂會" },
{ "en": "critic", "zh": "批評家；評論家；吹毛求疵的人" },
{ "en": "curtain call", "zh": "謝幕" },
{ "en": "editorial", "zh": "社論" },
{ "en": "finale", "zh": "結局；樂曲的最後部分" },
{ "en": "media", "zh": "媒體" },
{ "en": "performance", "zh": "演出；表現；性能" },
{ "en": "playwright", "zh": "劇作家" },
{ "en": "preview", "zh": "試映；預告片" },
{ "en": "rehearsal", "zh": "預演；排練" },
{ "en": "screen", "zh": "隔板；螢幕；螢光屏" },
{ "en": "stunt", "zh": "特技；噱頭" },
{ "en": "theater", "zh": "戲院；劇院" },
{ "en": "violin", "zh": "小提琴" },
{ "en": "aerobics", "zh": "有氧運動" },
{ "en": "coach", "zh": "教師；教練" },
{ "en": "compete", "zh": "競爭；比賽" },
{ "en": "defeat", "zh": "失敗；擊敗" },
{ "en": "fitness", "zh": "適合；恰當；身體健康" },
{ "en": "gym", "zh": "健身房；體育館" },
{ "en": "league", "zh": "聯盟；同盟" },
{ "en": "marathon", "zh": "馬拉松；耐力比賽" },
{ "en": "mountaineering", "zh": "登山運動" },
{ "en": "participate", "zh": "參與；參加" },
{ "en": "recreation", "zh": "娛樂；消遣" },
{ "en": "relaxation", "zh": "鬆弛；緩和；休息；娛樂" },
{ "en": "rigor", "zh": "嚴格；嚴苛；艱苦" },
{ "en": "soccer", "zh": "足球" },
{ "en": "stadium", "zh": "體育場" },
{ "en": "stroll", "zh": "散步；閒逛" },
{ "en": "surrender", "zh": "（向敵人）投降；放棄" },
{ "en": "time-out", "zh": "暫停" },
{ "en": "trophy", "zh": "獎品；獎盃；戰利品" },
{ "en": "usher", "zh": "引座員；招待員" },
{ "en": "billiards", "zh": "撞球" },
{ "en": "combative", "zh": "好戰的；好鬥的" },
{ "en": "default", "zh": "違約；棄權" },
{ "en": "defense", "zh": "保護；防衛" },
{ "en": "forfeit", "zh": "罰款；喪失" },
{ "en": "intensity", "zh": "強度；強烈" },
{ "en": "leisure", "zh": "空閒；閒暇時間" },
{ "en": "massage", "zh": "按摩；揉捏" },
{ "en": "muscle", "zh": "肌肉；力量" },
{ "en": "pastime", "zh": "娛樂；消遣" },
{ "en": "referee", "zh": "裁判員；仲裁者" },
{ "en": "replacement", "zh": "代替的人或物" },
{ "en": "runner-up", "zh": "第二名；亞軍" },
{ "en": "spectator", "zh": "觀眾；旁觀者" },
{ "en": "stretch", "zh": "伸張；伸開；伸展" },
{ "en": "surfing", "zh": "衝浪" },
{ "en": "tactic", "zh": "戰略；策略（常用複數）" },
{ "en": "tournament", "zh": "比賽；錦標賽" },
{ "en": "umpire", "zh": "裁判；仲裁" },
{ "en": "volleyball", "zh": "排球" },
{ "en": "alleviate", "zh": "減輕；緩和" },
{ "en": "bacteria", "zh": "細菌" },
{ "en": "collision", "zh": "碰撞；抵觸" },
{ "en": "compensation", "zh": "補償；賠償；報償" },
{ "en": "contagious", "zh": "接觸傳染的" },
{ "en": "crash", "zh": "相撞；碰撞；突然發出巨響" },
{ "en": "emergency room", "zh": "急診室" },
{ "en": "expiration date", "zh": "有效期限" },
{ "en": "general hospital", "zh": "綜合醫院" },
{ "en": "immune", "zh": "免除的；豁免的；免疫的" },
{ "en": "infection", "zh": "感染" },
{ "en": "investigator", "zh": "調查員" },
{ "en": "mandatory", "zh": "命令的；強制的；義務的" },
{ "en": "option", "zh": "選擇權；選擇之自由；可選擇的東西" },
{ "en": "outpatient", "zh": "門診病人" },
{ "en": "premium", "zh": "獎品；額外費用；保費" },
{ "en": "severe", "zh": "嚴苛的；嚴格的；嚴重的" },
{ "en": "stroke", "zh": "腦血管破裂或阻塞；中風" },
{ "en": "terms", "zh": "條文；條款；付款條件；價錢" },
{ "en": "vital", "zh": "非常必要的；及其重要的；攸關生死的" },
{ "en": "antibiotic", "zh": "抗生素" },
{ "en": "claim", "zh": "要求；聲稱" },
{ "en": "commission", "zh": "傭金" },
{ "en": "comprehensive", "zh": "全面的；廣泛的" },
{ "en": "coverage", "zh": "報導範圍；保險範圍" },
{ "en": "diagnose", "zh": "診斷；判斷" },
{ "en": "excruciating", "zh": "極痛苦的；極度的" },
{ "en": "fraud", "zh": "詐騙；騙局；騙子" },
{ "en": "handicap", "zh": "殘障；不利條件；障礙" },
{ "en": "indemnity", "zh": "損害保障；損害賠償" },
{ "en": "intensive care unit", "zh": "加護病房" },
{ "en": "liable", "zh": "有義務的；易於……的；傾向於……的" },
{ "en": "nutrition", "zh": "營養之供給或攝取；營養" },
{ "en": "organ donor", "zh": "器官捐贈者" },
{ "en": "pharmaceutical", "zh": "制藥的；藥品的" },
{ "en": "purification", "zh": "洗淨；淨化" },
{ "en": "side effect", "zh": "（藥物之）副作用" },
{ "en": "surgery", "zh": "（外科）手術" },
{ "en": "trauma", "zh": "外傷；心靈的傷" },
{ "en": "waive", "zh": "放棄；棄權" },
{ "en": "appliance", "zh": "設備；器具；工具；家用電器" },
{ "en": "burglar", "zh": "竊賊；夜間入屋行竊的小偷" },
{ "en": "community", "zh": "社區" },
{ "en": "electronics", "zh": "電子學" },
{ "en": "fire extinguisher", "zh": "滅火器" },
{ "en": "furniture", "zh": "傢俱" },
{ "en": "garbage disposal", "zh": "垃圾處理機" },
{ "en": "landlord", "zh": "地主；房東" },
{ "en": "laundry", "zh": "洗衣店；要洗或已洗好的衣物" },
{ "en": "lease", "zh": "租約；出租；租用" },
{ "en": "mattress", "zh": "床墊" },
{ "en": "mortgage", "zh": "抵押貨（借）款" },
{ "en": "ornament", "zh": "裝飾品" },
{ "en": "plumbing", "zh": "水管設施" },
{ "en": "possession", "zh": "所有；個人財產" },
{ "en": "real estate", "zh": "不動產" },
{ "en": "renovate", "zh": "更新；修復；恢復" },
{ "en": "rural", "zh": "鄉下；田園" },
{ "en": "suburb", "zh": "（常用複數）郊區；近郊" },
{ "en": "urban", "zh": "都市的；都市式的" },
{ "en": "balcony", "zh": "陽臺；包廂" },
{ "en": "chore", "zh": "家務難事；困難繁瑣無趣的工作" },
{ "en": "down payment", "zh": "頭期款；預付金；定金" },
{ "en": "fire alarm", "zh": "火災警報器" },
{ "en": "furnishings", "zh": "傢俱；室內陳設" },
{ "en": "garage", "zh": "車庫；修車廠" },
{ "en": "kitchenware", "zh": "廚房用具" },
{ "en": "laundromat", "zh": "自助洗衣店" },
{ "en": "lawn", "zh": "草坪；草地" },
{ "en": "loan shark", "zh": "放高利貸者" },
{ "en": "messy", "zh": "雜亂的；骯髒的" },
{ "en": "neighborhood", "zh": "街坊；住宅區；臨近地區" },
{ "en": "playground", "zh": "運動場；遊戲場；遊樂場" },
{ "en": "porch", "zh": "門廊；遊廊" },
{ "en": "property", "zh": "財產；地產" },
{ "en": "relocate", "zh": "重新安置；遷徙" },
{ "en": "residence", "zh": "住所；公館；居住" },
{ "en": "storage", "zh": "儲藏；藏室" },
{ "en": "tenant", "zh": "房客；承租人；佃戶" },
{ "en": "utility", "zh": "公共實業；實用" },
{ "en": "affection", "zh": "感情；鍾愛" },
{ "en": "anticipate", "zh": "預見；期待；在……之前行動；預先考慮；提前使用" },
{ "en": "brag", "zh": "自誇；吹噓" },
{ "en": "delighted", "zh": "欣喜的；愉快的" },
{ "en": "detest", "zh": "憎惡；痛恨；嫌惡" },
{ "en": "disgust", "zh": "作嘔；厭惡；反感；導致反感" },
{ "en": "distress", "zh": "悲痛；貧困；危難" },
{ "en": "enthusiastic", "zh": "熱心的；狂熱的" },
{ "en": "esteem", "zh": "好評；尊敬；極看重；尊重" },
{ "en": "fascination", "zh": "入迷；著迷；強烈吸引力；魅力" },
{ "en": "gloomy", "zh": "幽暗的；令人沮喪的；憂鬱的；沒有希望的" },
{ "en": "impartial", "zh": "不偏袒；無偏見的；公正的" },
{ "en": "impulsive", "zh": "衝動的" },
{ "en": "irritated", "zh": "被激怒的；發炎的；疼痛的" },
{ "en": "mad", "zh": "發瘋的；瘋狂的；著迷的；愚蠢的；生氣的" },
{ "en": "objective", "zh": "目標；客觀的" },
{ "en": "panic", "zh": "恐慌；使恐慌" },
{ "en": "prejudice", "zh": "偏見；歧視" },
{ "en": "repulsive", "zh": "使人反感的；令人厭惡的" },
{ "en": "tranquility", "zh": "平靜的；安寧" },
{ "en": "ambition", "zh": "雄心；野心" },
{ "en": "attraction", "zh": "吸引力；吸引人之物" },
{ "en": "contentment", "zh": "滿意；滿足" },
{ "en": "despair", "zh": "絕望；使人絕望的事物" },
{ "en": "devoted", "zh": "摯愛的；忠實的；熱忱的" },
{ "en": "disposition", "zh": "傾向；性格；氣質；性情" },
{ "en": "elegant", "zh": "高雅的；有品味的；上等的" },
{ "en": "entice", "zh": "誘惑；引誘" },
{ "en": "fancy", "zh": "精心設計的；特技的；花俏的；昂貴的" },
{ "en": "fondness", "zh": "鍾愛；溺愛；嗜好；癖好" },
{ "en": "hideous", "zh": "醜的嚇人；不忍睹的；醜惡的；可憎的" },
{ "en": "impression", "zh": "意念；印象；不太明確的感覺或想法" },
{ "en": "instinct", "zh": "天性；本能；直覺" },
{ "en": "jealous", "zh": "嫉妒的；羡慕的；唯恐失去的" },
{ "en": "nasty", "zh": "骯髒的；不道德的；惡毒的；令人不愉快的；嚴重的" },
{ "en": "optimistic", "zh": "樂觀的" },
{ "en": "perceive", "zh": "感知；察覺；理會" },
{ "en": "provoke", "zh": "激怒；引起；激起" },
{ "en": "startle", "zh": "驚嚇；使嚇一跳" },
{ "en": "upset", "zh": "使心煩意亂；使不舒服；使失敗；打翻" },
{ "en": "aspect", "zh": "面貌；方向；朝向" },
{ "en": "assumption", "zh": "假定；假設" },
{ "en": "attempt", "zh": "⑴企圖；攻擊 ⑵努力嘗試；企圖" },
{ "en": "call waiting", "zh": "電話插播" },
{ "en": "declaration", "zh": "宣佈；公佈；宣言" },
{ "en": "endeavor", "zh": "努力；盡力；試圖；嘗試" },
{ "en": "exceed", "zh": "超過；超出；超越" },
{ "en": "identity", "zh": "身份；本體；相同；同一" },
{ "en": "implication", "zh": "含義；暗示；牽連" },
{ "en": "inspire", "zh": "鼓舞；激發；引發" },
{ "en": "intention", "zh": "意圖；目的" },
{ "en": "interrupt", "zh": "打斷；中斷" },
{ "en": "manipulate", "zh": "操作；操縱" },
{ "en": "obstacle", "zh": "障礙物；阻礙" },
{ "en": "priority", "zh": "優先權；優先考慮的事" },
{ "en": "prohibit", "zh": "禁止；防止；阻止" },
{ "en": "reassure", "zh": "使安心；使放心；使恢復信心；再保證" },
{ "en": "remind", "zh": "提醒；使想起" },
{ "en": "sustain", "zh": "維持；持續；支撐；蒙受" },
{ "en": "undertake", "zh": "承擔；許諾；保證" },
{ "en": "alter", "zh": "改變；修改" },
{ "en": "assurance", "zh": "保證；擔保；自信；把握" },
{ "en": "clarify", "zh": "澄清；使純淨" },
{ "en": "discard", "zh": "拋棄；丟棄" },
{ "en": "entitle", "zh": "定名；使有資格" },
{ "en": "exhibition", "zh": "展覽會；表現" },
{ "en": "impact", "zh": "碰撞力；影響；行動" },
{ "en": "incentive", "zh": "鼓勵；誘因" },
{ "en": "instruct", "zh": "教授；指導；下命令；指示" },
{ "en": "interfere", "zh": "妨害；擾亂；介入；干涉" },
{ "en": "involve", "zh": "使捲入；牽涉；伴隨（指必然結果）" },
{ "en": "merit", "zh": "功勞；價值；優點" },
{ "en": "permit", "zh": "許可證；執照；准許；許可" },
{ "en": "proceed", "zh": "著手；繼續進行" },
{ "en": "protest", "zh": "抗議；反對" },
{ "en": "register", "zh": "⑴登記簿；註冊簿 ⑵記錄；註冊；登記姓名" },
{ "en": "risk", "zh": "風險；危險；使遭受危險；冒……的危險" },
{ "en": "submit", "zh": "認輸；使服從；提出" },
{ "en": "speculate", "zh": "沉思；思索；猜測；推測；投機" },
{ "en": "verify", "zh": "證明；證實；確認" },
{ "en": "absurd", "zh": "荒謬的；不合理的；違反常理的" },
{ "en": "adequate", "zh": "足夠的；適當的" },
{ "en": "ample", "zh": "廣大的；寬敞的；充足的" },
{ "en": "decent", "zh": "合宜的；得體的；適當的" },
{ "en": "dreadful", "zh": "令人恐怖的；令人害怕的" },
{ "en": "exceptional", "zh": "異常的；例外的；特別優秀" },
{ "en": "exquisite", "zh": "精細的；精美的；敏銳的；細緻的" },
{ "en": "farfetched", "zh": "牽強的；不大可信的；不自然的" },
{ "en": "in light of", "zh": "按照；根據" },
{ "en": "ingenious", "zh": "有巧思的；有創意的；靈敏的" },
{ "en": "instant", "zh": "立即的；（食品）快速方便的" },
{ "en": "legitimate", "zh": "合法的；正當的；婚生的" },
{ "en": "moderate", "zh": "中等的；適度的；有節制的；溫和的" },
{ "en": "oblivious", "zh": "遺忘的；不注意的；不在意的" },
{ "en": "random", "zh": "隨便的；無目的的" },
{ "en": "relevant", "zh": "有關的；切題的；有實際價值或重要性的" },
{ "en": "substantially", "zh": "相當大的；基本上；本質的" },
{ "en": "temporary", "zh": "暫時的；臨時的" },
{ "en": "unprecedented", "zh": "史無前例的；空前的" },
{ "en": "versatile", "zh": "多才多藝的；有多種用途的" },
{ "en": "accurate", "zh": "準確的；正確無誤的；精確的" },
{ "en": "alert", "zh": "警覺的；留心的；機警的；敏捷的" },
{ "en": "approximately", "zh": "大約；大概" },
{ "en": "distinctive", "zh": "與眾不同的；有特色的；顯著的" },
{ "en": "dynamic", "zh": "充滿活力的；動力的" },
{ "en": "excessive", "zh": "過多的；過度的；過分的" },
{ "en": "extraordinary", "zh": "特別的；格外的；值得注意的" },
{ "en": "fragile", "zh": "易碎的；易損壞的；脆弱的" },
{ "en": "inferior", "zh": "品質差的；下等的；下級的" },
{ "en": "initial", "zh": "開始的；最初的" },
{ "en": "irresistible", "zh": "極為誘人的；無法抗拒的" },
{ "en": "miscellaneous", "zh": "不同種類的；各式各樣的；混雜的" },
{ "en": "noteworthy", "zh": "值得注意的；顯著的" },
{ "en": "on and off", "zh": "斷斷續續的；偶爾；有時" },
{ "en": "rapid", "zh": "迅速的；快速的；快的" },
{ "en": "self-explanatory", "zh": "不需要加以說明的；不言自明的" },
{ "en": "sufficient", "zh": "足夠的" },
{ "en": "ultimately", "zh": "最後；最終" },
{ "en": "vague", "zh": "含糊不清的；模糊不清的" },
{ "en": "vivid", "zh": "生龍活虎的；鮮豔的；鮮明的；生動逼真的" },
{ "en": "equipment", "zh": "設備" }
];

let currentIndex = -1;
let showingTranslation = false;

const flashcard = document.getElementById("flashcard");

function nextCard() {
    let newIndex;
    do {
    newIndex = Math.floor(Math.random() * words.length);
    } while (newIndex === currentIndex);
    currentIndex = newIndex;
    showingTranslation = false;
    flashcard.textContent = words[currentIndex].en;
    speakWord(words[currentIndex].en);
}

flashcard.addEventListener("click", () => {
    if (showingTranslation) {
        flashcard.textContent = words[currentIndex].en;
        showingTranslation = false;
      } else {
        flashcard.textContent = words[currentIndex].zh;
        showingTranslation = true;
      }
    });

function speakWord(text) {
  const utterance = new SpeechSynthesisUtterance(text);
  utterance.lang = "en-US";
  utterance.rate = 0.9; // Speech speed adjustment (0.1 ~ 10)
  speechSynthesis.cancel(); // Stop the previous reading first
  speechSynthesis.speak(utterance);
}

function replay() {
      speakWord(words[currentIndex].en);
    }


// Initial display of the first
nextCard();

function goBack() {
    window.location.href = "https://ChiaYunn.github.io/front_page.html";
}